var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/general/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1jb072f._.js")
R.c("server/chunks/ssr/19xk_next_dist_esm_build_templates_app-page_1el18xs.js")
R.c("server/chunks/ssr/[root-of-the-server]__018f59i._.js")
R.c("server/chunks/ssr/19xk_next_dist_1nb5fh6._.js")
R.c("server/chunks/ssr/frontend_0nd5m4k._.js")
R.c("server/chunks/ssr/frontend_0_3xhts._.js")
R.c("server/chunks/ssr/19xk_next_dist_client_components_021ukj3._.js")
R.c("server/chunks/ssr/19xk_next_dist_client_components_builtin_unauthorized_098p3j3.js")
R.c("server/chunks/ssr/19xk_next_dist_client_components_builtin_global-error_0b1_q4t.js")
R.c("server/chunks/ssr/frontend_app_admin_layout_tsx_1u_99wk._.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_admin_general_page_actions_09c-3l3.js")
R.m(89042)
module.exports=R.m(89042).exports
