<?php

return [
    'form' => [
        'toolbar' => [
            'buttons' => [
                'back' => [
                    'label' => 'lang:admin::lang.button_icon_back',
                    'class' => 'btn btn-outline-secondary',
                    'href' => 'settings',
                ],
                'save' => [
                    'label' => 'lang:admin::lang.button_save',
                    'class' => 'btn btn-primary',
                    'data-request' => 'onSave',
                    'data-progress-indicator' => 'admin::lang.text_saving',
                ],
            ],
        ],
        'tabs' => [
            'fields' => [
                'guest_order' => [
                    'label' => 'lang:system::lang.settings.label_guest_order',
                    'tab' => 'lang:system::lang.settings.text_tab_title_order',
                    'type' => 'switch',
                    'on' => 'lang:admin::lang.text_yes',
                    'off' => 'lang:admin::lang.text_no',
                    'comment' => 'lang:system::lang.settings.help_guest_order',
                ],
                'location_order' => [
                    'label' => 'lang:system::lang.settings.label_location_order',
                    'tab' => 'lang:system::lang.settings.text_tab_title_order',
                    'type' => 'switch',
                    'default' => false,
                    'on' => 'lang:admin::lang.text_yes',
                    'off' => 'lang:admin::lang.text_no',
                    'comment' => 'lang:system::lang.settings.help_location_order',
                ],
                'order_email' => [
                    'label' => 'lang:system::lang.settings.label_order_email',
                    'tab' => 'lang:system::lang.settings.text_tab_title_order',
                    'type' => 'checkboxtoggle',
                    'options' => [
                        'customer' => 'lang:system::lang.settings.text_to_customer',
                        'admin' => 'lang:system::lang.settings.text_to_admin',
                        'location' => 'lang:system::lang.settings.text_to_location',
                    ],
                    'comment' => 'lang:system::lang.settings.help_order_email',
                ],
                'default_order_status' => [
                    'label' => 'lang:system::lang.settings.label_default_order_status',
                    'tab' => 'lang:system::lang.settings.text_tab_title_order',
                    'type' => 'selectlist',
                    'mode' => 'radio',
                    'options' => ['Admin\Models\Statuses_model', 'getDropdownOptionsForOrder'],
                    'comment' => 'lang:system::lang.settings.help_default_order_status',
                ],
                'processing_order_status' => [
                    'label' => 'lang:system::lang.settings.label_processing_order_status',
                    'tab' => 'lang:system::lang.settings.text_tab_title_order',
                    'type' => 'selectlist',
                    'options' => ['Admin\Models\Statuses_model', 'getDropdownOptionsForOrder'],
                    'comment' => 'lang:system::lang.settings.help_processing_order_status',
                ],
                'completed_order_status' => [
                    'label' => 'lang:system::lang.settings.label_completed_order_status',
                    'tab' => 'lang:system::lang.settings.text_tab_title_order',
                    'type' => 'selectlist',
                    'options' => ['Admin\Models\Statuses_model', 'getDropdownOptionsForOrder'],
                    'comment' => 'lang:system::lang.settings.help_completed_order_status',
                ],
                'canceled_order_status' => [
                    'label' => 'lang:system::lang.settings.label_canceled_order_status',
                    'tab' => 'lang:system::lang.settings.text_tab_title_order',
                    'type' => 'selectlist',
                    'mode' => 'radio',
                    'options' => ['Admin\Models\Statuses_model', 'getDropdownOptionsForOrder'],
                    'comment' => 'lang:system::lang.settings.help_canceled_order_status',
                ],


                'eta_section' => [
                    'tab' => 'lang:system::lang.settings.text_tab_title_order',
                    'type' => 'section',
                    'label' => 'Order Timing & Smart ETA',
                    'comment' => 'Smart ETA uses item prep times and current order load. No external AI required.',
                ],
                'enable_customer_eta' => ['label'=>'Show ETA to customers','tab'=>'lang:system::lang.settings.text_tab_title_order','type'=>'switch','default'=>true,'on'=>'lang:admin::lang.text_yes','off'=>'lang:admin::lang.text_no'],
                'smart_eta_enabled' => ['label'=>'Smart ETA','tab'=>'lang:system::lang.settings.text_tab_title_order','type'=>'switch','default'=>true,'on'=>'lang:admin::lang.text_yes','off'=>'lang:admin::lang.text_no'],
                'eta_default_prep_minutes' => ['label'=>'Default prep time','tab'=>'lang:system::lang.settings.text_tab_title_order','type'=>'number','default'=>15,'attributes'=>['min'=>1,'max'=>240]],
                'eta_order_load_window_minutes' => ['label'=>'Kitchen load window','tab'=>'lang:system::lang.settings.text_tab_title_order','type'=>'select','default'=>30,'options'=>[15=>'15',30=>'30',45=>'45',60=>'60']],
                'eta_busy_order_threshold' => ['label'=>'Busy threshold','tab'=>'lang:system::lang.settings.text_tab_title_order','type'=>'number','default'=>6],
                'eta_very_busy_order_threshold' => ['label'=>'Very busy threshold','tab'=>'lang:system::lang.settings.text_tab_title_order','type'=>'number','default'=>13],
                'eta_busy_extra_minutes' => ['label'=>'Busy extra minutes','tab'=>'lang:system::lang.settings.text_tab_title_order','type'=>'number','default'=>5],
                'eta_very_busy_extra_minutes' => ['label'=>'Very busy extra minutes','tab'=>'lang:system::lang.settings.text_tab_title_order','type'=>'number','default'=>10],
                'eta_round_to_nearest_minutes' => ['label'=>'Round ETA','tab'=>'lang:system::lang.settings.text_tab_title_order','type'=>'select','default'=>5,'options'=>[1=>'1',5=>'5',10=>'10']],
                'eta_max_minutes' => ['label'=>'Maximum ETA','tab'=>'lang:system::lang.settings.text_tab_title_order','type'=>'number','default'=>90,'attributes'=>['min'=>10,'max'=>240]],
                'eta_hint_text' => ['label'=>'ETA note','tab'=>'lang:system::lang.settings.text_tab_title_order','type'=>'textarea','default'=>'Estimated time may change depending on kitchen load.'],

                'reservation_email' => [
                    'label' => 'lang:system::lang.settings.label_reservation_email',
                    'tab' => 'lang:system::lang.settings.text_tab_title_reservation',
                    'type' => 'checkboxtoggle',
                    'options' => [
                        'customer' => 'lang:system::lang.settings.text_to_customer',
                        'admin' => 'lang:system::lang.settings.text_to_admin',
                        'location' => 'lang:system::lang.settings.text_to_location',
                    ],
                    'comment' => 'lang:system::lang.settings.help_reservation_email',
                ],
                'default_reservation_status' => [
                    'label' => 'lang:system::lang.settings.label_default_reservation_status',
                    'tab' => 'lang:system::lang.settings.text_tab_title_reservation',
                    'type' => 'selectlist',
                    'mode' => 'radio',
                    'options' => ['Admin\Models\Statuses_model', 'getDropdownOptionsForReservation'],
                    'comment' => 'lang:system::lang.settings.help_default_reservation_status',
                ],
                'confirmed_reservation_status' => [
                    'label' => 'lang:system::lang.settings.label_confirmed_reservation_status',
                    'tab' => 'lang:system::lang.settings.text_tab_title_reservation',
                    'type' => 'selectlist',
                    'mode' => 'radio',
                    'options' => ['Admin\Models\Statuses_model', 'getDropdownOptionsForReservation'],
                    'comment' => 'lang:system::lang.settings.help_confirmed_reservation_status',
                ],
                'canceled_reservation_status' => [
                    'label' => 'lang:system::lang.settings.label_canceled_reservation_status',
                    'tab' => 'lang:system::lang.settings.text_tab_title_reservation',
                    'type' => 'selectlist',
                    'mode' => 'radio',
                    'options' => ['Admin\Models\Statuses_model', 'getDropdownOptionsForReservation'],
                    'comment' => 'lang:system::lang.settings.help_canceled_reservation_status',
                ],

                'invoice_section_branding' => [
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'section',
                    'label' => 'Branding',
                ],
                'invoice_logo' => [
                    'label' => 'lang:system::lang.settings.label_invoice_logo',
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'mediafinder',
                    'span' => 'left',
                    'mode' => 'grid',
                    'comment' => 'lang:system::lang.settings.help_invoice_logo',
                ],
                'invoice_section_customer' => [
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'section',
                    'label' => 'Customer Invoice',
                ],
                'invoice_customer_template' => [
                    'label' => 'Customer Invoice Template',
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'selectlist',
                    'mode' => 'radio',
                    'default' => 'classic',
                    'options' => [
                        'classic' => 'Classic Receipt',
                        'modern' => 'Modern Compact',
                        'minimal' => 'Minimal Clean',
                    ],
                    'comment' => 'Choose the customer invoice receipt style.',
                ],
                'invoice_customer_footer_text' => [
                    'label' => 'Customer Invoice Footer',
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'textarea',
                    'default' => 'Thank you',
                    'comment' => 'Optional short footer text for customer invoice receipts.',
                ],
                'invoice_preview_widget' => [
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'partial',
                    'path' => 'settings/invoice_preview',
                    'span' => 'right',
                ],
                'invoice_section_numbering' => [
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'section',
                    'label' => 'Numbering',
                ],
                'invoice_prefix_preset' => [
                    'label' => 'Invoice Prefix Preset',
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'select',
                    'default' => 'custom',
                    'options' => [
                        '' => 'No prefix',
                        'INV-{year}-' => 'Yearly: INV-{year}-',
                        'INV-{year}{month}-' => 'Monthly: INV-{year}{month}-',
                        'INV-{year}{month}{day}-' => 'Daily: INV-{year}{month}{day}-',
                        'custom' => 'Custom',
                    ],
                ],
                'invoice_prefix' => [
                    'label' => 'lang:system::lang.settings.label_invoice_prefix',
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'text',
                    'span' => 'left',
                    'comment' => 'lang:system::lang.settings.help_invoice_prefix',
                ],
                'invoice_section_print' => [
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'section',
                    'label' => 'Print Layout',
                ],
                'invoice_receipt_mode' => [
                    'label' => 'lang:system::lang.settings.label_invoice_receipt_mode',
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'switch',
                    'default' => true,
                    'on' => 'lang:admin::lang.text_yes',
                    'off' => 'lang:admin::lang.text_no',
                ],
                'invoice_paper_width' => [
                    'label' => 'lang:system::lang.settings.label_invoice_paper_width',
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'selectlist',
                    'mode' => 'radio',
                    'default' => '80mm',
                    'options' => ['58mm'=>'58mm','80mm'=>'80mm (Thermal)','112mm'=>'112mm','a4'=>'A4'],
                ],
                'invoice_compact_mode' => [ 'label'=>'lang:system::lang.settings.label_invoice_compact_mode','tab'=>'lang:system::lang.settings.text_tab_title_invoice','type'=>'switch','default'=>true,'on'=>'lang:admin::lang.text_yes','off'=>'lang:admin::lang.text_no'],
                'invoice_font_size_preset' => [ 'label'=>'lang:system::lang.settings.label_invoice_font_size_preset','tab'=>'lang:system::lang.settings.text_tab_title_invoice','type'=>'selectlist','mode'=>'radio','default'=>'normal','options'=>['small'=>'Small','normal'=>'Normal']],
                'invoice_show_logo' => [ 'label'=>'lang:system::lang.settings.label_invoice_show_logo','tab'=>'lang:system::lang.settings.text_tab_title_invoice','type'=>'switch','default'=>true,'on'=>'lang:admin::lang.text_yes','off'=>'lang:admin::lang.text_no'],
                'invoice_section_fiscal' => [ 'tab'=>'lang:system::lang.settings.text_tab_title_invoice','type'=>'section','label'=>'Fiscal / Compliance'],
                'invoice_show_qr' => [ 'label'=>'lang:system::lang.settings.label_invoice_show_qr','tab'=>'lang:system::lang.settings.text_tab_title_invoice','type'=>'switch','default'=>true,'on'=>'lang:admin::lang.text_yes','off'=>'lang:admin::lang.text_no'],
                'invoice_show_fiskaly' => [ 'label'=>'lang:system::lang.settings.label_invoice_show_fiskaly','tab'=>'lang:system::lang.settings.text_tab_title_invoice','type'=>'switch','default'=>true,'on'=>'lang:admin::lang.text_yes','off'=>'lang:admin::lang.text_no'],
                'invoice_section_advanced' => [ 'tab'=>'lang:system::lang.settings.text_tab_title_invoice','type'=>'section','label'=>'Advanced Print Automation'],
                'invoice_auto_print_dialog' => [ 'label'=>'lang:system::lang.settings.label_invoice_auto_print_dialog','tab'=>'lang:system::lang.settings.text_tab_title_invoice','type'=>'switch','default'=>false,'on'=>'lang:admin::lang.text_yes','off'=>'lang:admin::lang.text_no'],
                'invoice_auto_print_after_paid' => [ 'label'=>'lang:system::lang.settings.label_invoice_auto_print_after_paid','tab'=>'lang:system::lang.settings.text_tab_title_invoice','type'=>'switch','default'=>false,'on'=>'lang:admin::lang.text_yes','off'=>'lang:admin::lang.text_no','comment'=>'Requires supported POS/browser print workflow.'],
                'invoice_print_hint' => [ 'label'=>'lang:system::lang.settings.label_invoice_print_hint','tab'=>'lang:system::lang.settings.text_tab_title_invoice','type'=>'textarea','default'=>'For best POS printing in Edge/Chrome: choose 80mm paper, scale 100%, margins None, headers/footers Off, and enable background graphics.'],
            ],
        ],
    ],
];
