<?php

return [
    'form' => [
        'toolbar' => [
            'buttons' => [
                'back' => [
                    'label' => 'lang:admin::lang.button_icon_back',
                    'class' => 'btn btn-outline-secondary',
                    'href' => 'settings',
                ],
                'save' => [
                    'label' => 'lang:admin::lang.button_save',
                    'class' => 'btn btn-primary',
                    'data-request' => 'onSave',
                    'data-progress-indicator' => 'admin::lang.text_saving',
                ],
            ],
        ],
        'tabs' => [
            'fields' => [
                'guest_order' => [
                    'label' => 'lang:system::lang.settings.label_guest_order',
                    'tab' => 'lang:system::lang.settings.text_tab_title_order',
                    'type' => 'switch',
                    'on' => 'lang:admin::lang.text_yes',
                    'off' => 'lang:admin::lang.text_no',
                    'comment' => 'lang:system::lang.settings.help_guest_order',
                ],
                'location_order' => [
                    'label' => 'lang:system::lang.settings.label_location_order',
                    'tab' => 'lang:system::lang.settings.text_tab_title_order',
                    'type' => 'switch',
                    'default' => false,
                    'on' => 'lang:admin::lang.text_yes',
                    'off' => 'lang:admin::lang.text_no',
                    'comment' => 'lang:system::lang.settings.help_location_order',
                ],
                'order_email' => [
                    'label' => 'lang:system::lang.settings.label_order_email',
                    'tab' => 'lang:system::lang.settings.text_tab_title_order',
                    'type' => 'checkboxtoggle',
                    'options' => [
                        'customer' => 'lang:system::lang.settings.text_to_customer',
                        'admin' => 'lang:system::lang.settings.text_to_admin',
                        'location' => 'lang:system::lang.settings.text_to_location',
                    ],
                    'comment' => 'lang:system::lang.settings.help_order_email',
                ],
                'default_order_status' => [
                    'label' => 'lang:system::lang.settings.label_default_order_status',
                    'tab' => 'lang:system::lang.settings.text_tab_title_order',
                    'type' => 'selectlist',
                    'mode' => 'radio',
                    'options' => ['Admin\Models\Statuses_model', 'getDropdownOptionsForOrder'],
                    'comment' => 'lang:system::lang.settings.help_default_order_status',
                ],
                'processing_order_status' => [
                    'label' => 'lang:system::lang.settings.label_processing_order_status',
                    'tab' => 'lang:system::lang.settings.text_tab_title_order',
                    'type' => 'selectlist',
                    'options' => ['Admin\Models\Statuses_model', 'getDropdownOptionsForOrder'],
                    'comment' => 'lang:system::lang.settings.help_processing_order_status',
                ],
                'completed_order_status' => [
                    'label' => 'lang:system::lang.settings.label_completed_order_status',
                    'tab' => 'lang:system::lang.settings.text_tab_title_order',
                    'type' => 'selectlist',
                    'options' => ['Admin\Models\Statuses_model', 'getDropdownOptionsForOrder'],
                    'comment' => 'lang:system::lang.settings.help_completed_order_status',
                ],
                'canceled_order_status' => [
                    'label' => 'lang:system::lang.settings.label_canceled_order_status',
                    'tab' => 'lang:system::lang.settings.text_tab_title_order',
                    'type' => 'selectlist',
                    'mode' => 'radio',
                    'options' => ['Admin\Models\Statuses_model', 'getDropdownOptionsForOrder'],
                    'comment' => 'lang:system::lang.settings.help_canceled_order_status',
                ],

                'reservation_email' => [
                    'label' => 'lang:system::lang.settings.label_reservation_email',
                    'tab' => 'lang:system::lang.settings.text_tab_title_reservation',
                    'type' => 'checkboxtoggle',
                    'options' => [
                        'customer' => 'lang:system::lang.settings.text_to_customer',
                        'admin' => 'lang:system::lang.settings.text_to_admin',
                        'location' => 'lang:system::lang.settings.text_to_location',
                    ],
                    'comment' => 'lang:system::lang.settings.help_reservation_email',
                ],
                'default_reservation_status' => [
                    'label' => 'lang:system::lang.settings.label_default_reservation_status',
                    'tab' => 'lang:system::lang.settings.text_tab_title_reservation',
                    'type' => 'selectlist',
                    'mode' => 'radio',
                    'options' => ['Admin\Models\Statuses_model', 'getDropdownOptionsForReservation'],
                    'comment' => 'lang:system::lang.settings.help_default_reservation_status',
                ],
                'confirmed_reservation_status' => [
                    'label' => 'lang:system::lang.settings.label_confirmed_reservation_status',
                    'tab' => 'lang:system::lang.settings.text_tab_title_reservation',
                    'type' => 'selectlist',
                    'mode' => 'radio',
                    'options' => ['Admin\Models\Statuses_model', 'getDropdownOptionsForReservation'],
                    'comment' => 'lang:system::lang.settings.help_confirmed_reservation_status',
                ],
                'canceled_reservation_status' => [
                    'label' => 'lang:system::lang.settings.label_canceled_reservation_status',
                    'tab' => 'lang:system::lang.settings.text_tab_title_reservation',
                    'type' => 'selectlist',
                    'mode' => 'radio',
                    'options' => ['Admin\Models\Statuses_model', 'getDropdownOptionsForReservation'],
                    'comment' => 'lang:system::lang.settings.help_canceled_reservation_status',
                ],

                'invoice_prefix' => [
                    'label' => 'lang:system::lang.settings.label_invoice_prefix',
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'text',
                    'span' => 'left',
                    'comment' => 'lang:system::lang.settings.help_invoice_prefix',
                ],
                'invoice_logo' => [
                    'label' => 'lang:system::lang.settings.label_invoice_logo',
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'mediafinder',
                    'span' => 'right',
                    'mode' => 'grid',
                    'comment' => 'lang:system::lang.settings.help_invoice_logo',
                ],
                'invoice_receipt_mode' => [
                    'label' => 'lang:system::lang.settings.label_invoice_receipt_mode',
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'switch',
                    'default' => true,
                    'on' => 'lang:admin::lang.text_yes',
                    'off' => 'lang:admin::lang.text_no',
                    'comment' => 'lang:system::lang.settings.help_invoice_receipt_mode',
                ],
                'invoice_paper_width' => [
                    'label' => 'lang:system::lang.settings.label_invoice_paper_width',
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'selectlist',
                    'mode' => 'radio',
                    'default' => '80mm',
                    'options' => [
                        '80mm' => '80mm (Thermal)',
                        'a4' => 'A4',
                    ],
                    'comment' => 'lang:system::lang.settings.help_invoice_paper_width',
                ],
                'invoice_auto_print_dialog' => [
                    'label' => 'lang:system::lang.settings.label_invoice_auto_print_dialog',
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'switch',
                    'default' => false,
                    'on' => 'lang:admin::lang.text_yes',
                    'off' => 'lang:admin::lang.text_no',
                    'comment' => 'lang:system::lang.settings.help_invoice_auto_print_dialog',
                ],
                'invoice_show_logo' => [
                    'label' => 'lang:system::lang.settings.label_invoice_show_logo',
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'switch',
                    'default' => true,
                    'on' => 'lang:admin::lang.text_yes',
                    'off' => 'lang:admin::lang.text_no',
                    'comment' => 'lang:system::lang.settings.help_invoice_show_logo',
                ],
                'invoice_show_qr' => [
                    'label' => 'lang:system::lang.settings.label_invoice_show_qr',
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'switch',
                    'default' => true,
                    'on' => 'lang:admin::lang.text_yes',
                    'off' => 'lang:admin::lang.text_no',
                    'comment' => 'lang:system::lang.settings.help_invoice_show_qr',
                ],
                'invoice_show_fiskaly' => [
                    'label' => 'lang:system::lang.settings.label_invoice_show_fiskaly',
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'switch',
                    'default' => true,
                    'on' => 'lang:admin::lang.text_yes',
                    'off' => 'lang:admin::lang.text_no',
                    'comment' => 'lang:system::lang.settings.help_invoice_show_fiskaly',
                ],
                'invoice_compact_mode' => [
                    'label' => 'lang:system::lang.settings.label_invoice_compact_mode',
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'switch',
                    'default' => true,
                    'on' => 'lang:admin::lang.text_yes',
                    'off' => 'lang:admin::lang.text_no',
                    'comment' => 'lang:system::lang.settings.help_invoice_compact_mode',
                ],
                'invoice_font_size_preset' => [
                    'label' => 'lang:system::lang.settings.label_invoice_font_size_preset',
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'selectlist',
                    'mode' => 'radio',
                    'default' => 'normal',
                    'options' => [
                        'small' => 'Small',
                        'normal' => 'Normal',
                    ],
                    'comment' => 'lang:system::lang.settings.help_invoice_font_size_preset',
                ],
                'invoice_print_hint' => [
                    'label' => 'lang:system::lang.settings.label_invoice_print_hint',
                    'tab' => 'lang:system::lang.settings.text_tab_title_invoice',
                    'type' => 'textarea',
                    'default' => 'For best POS printing in Edge/Chrome: choose 80mm paper, scale 100%, margins None, headers/footers Off, and enable background graphics.',
                    'comment' => 'lang:system::lang.settings.help_invoice_print_hint',
                ],
            ],
        ],
    ],
];
