@extends('admin::superadmin_r2.layout')
@section('title','Restaurants')
@section('page_title','Restaurants')
@section('page_subtitle','Create, review and manage PayMyDine tenants')
@section('content')
<div class="hero"><div><h2>Restaurants</h2><p>Central tenant registry and onboarding.</p></div></div>
<div class="grid2">
<div class="card"><div class="card-head"><div><h3>Restaurant registry</h3><p>Search by name, domain, database or email.</p></div></div><form class="filters" method="GET" action="/superadmin/new"><input name="q" value="{{ $search }}" placeholder="Search restaurants"><select name="status"><option value="">All statuses</option><option value="active" {{ $status==='active'?'selected':'' }}>Active</option><option value="disabled" {{ $status==='disabled'?'selected':'' }}>Disabled</option><option value="removed" {{ $status==='removed'?'selected':'' }}>Removed</option></select><button class="btn btn-soft" type="submit">Filter</button></form><div style="height:12px"></div><div class="table-wrap"><table><thead><tr><th>Restaurant</th><th>Domain</th><th>Database</th><th>Period</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($tenants as $tenant)<tr><td><span class="tenant-name">{{ $tenant->name }}</span><span class="sub">{{ $tenant->email }}</span></td><td>{{ $tenant->domain }}</td><td>{{ $tenant->database }}</td><td>{{ $tenant->start }} → {{ $tenant->end }}</td><td><span class="badge {{ $tenant->status==='active'?'ok':($tenant->status==='removed'?'warn':'bad') }}">{{ $tenant->status }}</span></td><td><div style="display:flex;gap:6px;align-items:center;flex-wrap:wrap">@if($tenant->status==='removed')<form method="POST" action="/superadmin/tenants/restore">@csrf<input type="hidden" name="id" value="{{ $tenant->id }}"><button class="btn btn-soft" type="submit">Restore</button></form>@else<a class="btn btn-soft" href="/superadmin/tenants/{{ $tenant->id }}/edit">Edit</a><form method="POST" action="/superadmin/tenants/status" style="display:flex;gap:6px">@csrf<input type="hidden" name="id" value="{{ $tenant->id }}"><select name="status" style="border:1px solid #dfe9e5;border-radius:9px;padding:7px"><option value="active" {{ $tenant->status==='active'?'selected':'' }}>Active</option><option value="disabled" {{ $tenant->status==='disabled'?'selected':'' }}>Disabled</option></select><button class="btn btn-soft" type="submit">Save</button></form>@if($tenant->status==='disabled')<form method="POST" action="/superadmin/tenants/remove" onsubmit="return confirm('Remove {{ addslashes($tenant->name) }} from service? The tenant will stay offline and its database will be retained for recovery.')">@csrf<input type="hidden" name="id" value="{{ $tenant->id }}"><button class="btn btn-danger" type="submit">Remove</button></form>@endif @endif</div></td></tr>@empty<tr><td colspan="6" class="empty">No tenants found.</td></tr>@endforelse</tbody></table></div><div style="margin-top:12px">{{ $tenants->links() }}</div></div>
<div class="card"><div class="card-head"><div><h3>Create restaurant</h3><p>Creates a clean tenant database and provisions its PayMyDine subdomain/TLS. New tenants start without demo restaurant data.</p></div></div><form method="POST" action="/superadmin/new/store">@csrf<div class="field-grid"><div class="field"><label>Restaurant name</label><input name="name" value="{{ old('name') }}" required></div><div class="field"><label>Tenant subdomain</label><input name="domain" value="{{ old('domain') }}" placeholder="restaurant" autocomplete="off" required><span class="sub">Enter <strong>restaurant</strong> or <strong>restaurant.paymydine.com</strong>. The PayMyDine suffix is added automatically.</span></div><div class="field"><label>Database</label><input name="database" value="{{ old('database') }}" placeholder="restaurant" required></div><div class="field"><label>Email</label><input type="email" name="email" value="{{ old('email') }}" required></div><div class="field"><label>Phone</label><input name="phone" value="{{ old('phone') }}" required></div><div class="field"><label>Country</label><input name="country" value="{{ old('country','Germany') }}" required></div><div class="field"><label>Start date</label><input type="date" name="start" value="{{ old('start',now()->toDateString()) }}" required></div><div class="field"><label>End date</label><input type="date" name="end" value="{{ old('end',now()->addYear()->toDateString()) }}" required></div><div class="field"><label>Plan / type</label><input name="type" value="{{ old('type','People') }}" required></div><div class="field full"><label>Description</label><textarea name="description">{{ old('description') }}</textarea></div><div class="field full"><button class="btn btn-primary" type="submit">Create restaurant</button></div></div></form></div>
</div>
@endsection
