@include('admin::pmddevices._v2_boot')
@php $pmdFormWidget = $this->widgets['form'] ?? null; try { if ($pmdFormWidget) $pmdFormWidget->render(['useContainer'=>false]); } catch (\Throwable $e) {} @endphp
<div id="pmd-restaurant-profile" data-pmd-restaurant-profile data-pmd-device-settings-v2="biometric-edit">
    @include('admin::pmddevices._v2_header',['pmdSuiteTitle'=>'Edit biometric device','pmdSuiteBackUrl'=>admin_url('biometric_devices?tab=devices'),'pmdSuiteSave'=>true,'pmdSuiteDelete'=>true])
    {!! form_open(['id'=>'pmd-restaurant-profile-form','role'=>'form','method'=>'PATCH']) !!}
    <section class="pmd-profile-section pmd-profile-section--rose"><div class="pmd-profile-card"><div class="pmd-profile-card__header"><div class="pmd-profile-section-icon"><svg viewBox="0 0 24 24"><path d="M8 8a6 6 0 0 1 10 4c0 4-1 7-3 9M6 12a6 6 0 0 1 10-4"></path></svg></div><div><h2>Device connection</h2><p>Name, address, serial and state.</p></div></div><div class="pmd-profile-card__body"><div class="pmd-profile-grid pmd-profile-grid--2 pmd-device-native-form">@foreach(['name','ip','port','status','serial_number','description'] as $pmdName) @include('admin::pmddevices._v2_field',['pmdFormWidget'=>$pmdFormWidget,'pmdFieldName'=>$pmdName]) @endforeach</div></div></div></section>
    <section class="pmd-profile-section pmd-profile-section--cyan"><div class="pmd-profile-card"><div class="pmd-profile-card__header"><div class="pmd-profile-section-icon"><svg viewBox="0 0 24 24"><path d="M4 12h16M12 4v16"></path></svg></div><div><h2>Device tools</h2><p>Existing connection and synchronization handlers.</p></div></div><div class="pmd-profile-card__body"><div class="pmd-device-actions"><button type="button" class="pmd-device-action" data-request="onTestConnection">Test connection</button><button type="button" class="pmd-device-action" data-request="onSyncStaff" data-request-confirm="Sync all staff members to this device?">Sync staff</button><button type="button" class="pmd-device-action pmd-device-action--primary" data-request="onSyncAttendance" data-request-confirm="Sync attendance data from this device?">Sync attendance</button></div></div></div></section>
    <div class="pmd-profile-bottom-save"><button type="button" class="pmd-profile-bottom-save__button" data-request="onSave" data-request-form="#pmd-restaurant-profile-form" data-request-flash><svg viewBox="0 0 24 24"><path d="M20 6 9 17l-5-5"></path></svg><span>Save changes</span></button></div>{!! form_close() !!}
</div>
