@include('admin::pmddevices._v2_boot')
@php $activeTab = request('tab','attendance'); @endphp
<div id="pmd-restaurant-profile" data-pmd-restaurant-profile data-pmd-device-settings-v2="biometric">
    @include('admin::pmddevices._v2_header',['pmdSuiteTitle'=>'Biometric devices','pmdSuiteBackUrl'=>admin_url('pmddevices'),'pmdSuiteActionUrl'=>admin_url('biometric_devices/create'),'pmdSuiteActionTitle'=>'Create biometric device'])
    <section class="pmd-profile-section pmd-profile-section--rose"><div class="pmd-profile-card"><div class="pmd-profile-card__header"><div class="pmd-profile-section-icon"><svg viewBox="0 0 24 24"><path d="M8 8a6 6 0 0 1 10 4c0 4-1 7-3 9M6 12a6 6 0 0 1 10-4M6 16c1-2 1-4 1-5M10 21c2-3 3-6 3-9a2 2 0 0 0-4 0c0 4-1 6-2 8"></path></svg></div><div><h2>Biometric & attendance</h2><p>Device management, staff enrollment, attendance and reports in one Settings page.</p></div></div><div class="pmd-profile-card__body pmd-device-native-content">
        <div class="tab-heading"><ul class="form-nav nav nav-tabs"><li class="nav-item"><a class="nav-link {{ $activeTab==='attendance'?'active':'' }}" href="{{ admin_url('biometric_devices?tab=attendance') }}">Staff attendance</a></li><li class="nav-item"><a class="nav-link {{ $activeTab==='reports'?'active':'' }}" href="{{ admin_url('biometric_devices?tab=reports') }}">Reports</a></li><li class="nav-item"><a class="nav-link {{ $activeTab==='management'?'active':'' }}" href="{{ admin_url('biometric_devices?tab=management') }}">Device management</a></li><li class="nav-item"><a class="nav-link {{ $activeTab==='devices'?'active':'' }}" href="{{ admin_url('biometric_devices?tab=devices') }}">Devices</a></li><li class="nav-item"><a class="nav-link {{ $activeTab==='enroll'?'active':'' }}" href="{{ admin_url('biometric_devices?tab=enroll') }}">Enroll staff</a></li></ul></div>
        <div class="tab-content">@if($activeTab==='devices')<div class="pmd-device-native-list">{!! $this->renderList() !!}</div>@elseif($activeTab==='management') @include('admin::biometricdevices.device_management') @elseif($activeTab==='enroll') @include('admin::biometricdevices.enroll_staff') @elseif($activeTab==='reports') @include('admin::biometricdevices.reports') @else @include('admin::biometricdevices.attendance_list') @endif</div>
    </div></div></section>
</div>
