// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/menu" | "/payment/return" | "/preview" | "/preview/[themeId]" | "/table/[tableId]" | "/valet"
type AppRouteHandlerRoutes = "/api/bootstrap" | "/api/health" | "/api/locale" | "/api/media/[...path]" | "/api/v1/[...path]" | "/api/v2/frontend-theme" | "/assets/media/[...path]" | "/pmd-media/[...path]" | "/settings" | "/simple-theme" | "/storage/[...path]" | "/tip-settings" | "/uploads/[...path]" | "/validate-coupon" | "/vat-settings"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/bootstrap": {}
  "/api/health": {}
  "/api/locale": {}
  "/api/media/[...path]": { "path": string[]; }
  "/api/v1/[...path]": { "path": string[]; }
  "/api/v2/frontend-theme": {}
  "/assets/media/[...path]": { "path": string[]; }
  "/menu": {}
  "/payment/return": {}
  "/pmd-media/[...path]": { "path": string[]; }
  "/preview": {}
  "/preview/[themeId]": { "themeId": string; }
  "/settings": {}
  "/simple-theme": {}
  "/storage/[...path]": { "path": string[]; }
  "/table/[tableId]": { "tableId": string; }
  "/tip-settings": {}
  "/uploads/[...path]": { "path": string[]; }
  "/valet": {}
  "/validate-coupon": {}
  "/vat-settings": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
