@include('admin::pmddevices._v2_boot')
@php
$pmdFormWidget = $this->widgets['form'] ?? null; try { if ($pmdFormWidget) $pmdFormWidget->render(['useContainer'=>false]); } catch (\Throwable $e) {}
$pmdStatus = $localHardwareStatus ?? ['state'=>'not_configured','message'=>'Local hardware status unavailable.'];
$pmdLocalPrinters = $pmdStatus['localPrinters'] ?? [];
@endphp
<div id="pmd-restaurant-profile" data-pmd-restaurant-profile data-pmd-device-settings-v2="cash-edit">
    @include('admin::pmddevices._v2_header',['pmdSuiteTitle'=>'Edit cash drawer','pmdSuiteBackUrl'=>admin_url('cash_drawers'),'pmdSuiteSave'=>true,'pmdSuiteDelete'=>true])
    {!! form_open(['id'=>'pmd-restaurant-profile-form','role'=>'form','method'=>'PATCH']) !!}
    <section class="pmd-profile-section"><div class="pmd-profile-card"><div class="pmd-profile-card__header"><div class="pmd-profile-section-icon"><svg viewBox="0 0 24 24"><rect x="3" y="7" width="18" height="12" rx="2"></rect><path d="M3 11h18M8 15h.01"></path></svg></div><div><h2>Drawer setup</h2><p>Local POS mapping and automatic opening behavior.</p></div></div><div class="pmd-profile-card__body"><div class="pmd-profile-grid pmd-profile-grid--2 pmd-device-native-form">@foreach(['name','status','local_pos_device_id','printer_id','auto_open_on_cash','test_on_save'] as $pmdName) @include('admin::pmddevices._v2_field',['pmdFormWidget'=>$pmdFormWidget,'pmdFieldName'=>$pmdName]) @endforeach</div></div></div></section>
    <section class="pmd-profile-section pmd-profile-section--cyan"><div class="pmd-profile-card"><div class="pmd-profile-card__header"><div class="pmd-profile-section-icon"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"></circle><path d="M4 12h3M17 12h3M12 4v3M12 17v3"></path></svg></div><div><h2>Connection status & tools</h2><p>{{ $pmdStatus['message'] ?? 'Unknown status.' }}</p></div></div><div class="pmd-profile-card__body">
        <div class="pmd-device-status-grid"><div class="pmd-device-status-card"><span>Local agent</span><strong>{{ ($pmdStatus['state'] ?? '') === 'online' ? 'Online' : 'Offline / not configured' }}</strong></div><div class="pmd-device-status-card"><span>Terminal</span><strong>{{ $pmdStatus['device']->name ?? 'Not configured' }}</strong></div><div class="pmd-device-status-card"><span>Last seen</span><strong>{{ $pmdStatus['device']->last_seen_at ?? 'Never' }}</strong></div><div class="pmd-device-status-card"><span>Last command</span><strong>{{ $pmdStatus['drawer']->last_command_status ?? 'None' }}</strong></div></div>
        <div style="margin-top:14px"><div class="pmd-profile-grid pmd-profile-grid--2"><label class="pmd-profile-field"><span>Local printer</span><select name="local_printer_name" id="pmd-local-printer-name"><option value="">Select printer from terminal...</option>@foreach($pmdLocalPrinters as $printer) @php($pmdPrinterName=$printer['name'] ?? null) @php($pmdPrinterTarget=$printer['port_name'] ?? $pmdPrinterName) @if($pmdPrinterName)<option value="{{ $pmdPrinterName }}" data-target="{{ $pmdPrinterTarget }}">{{ $pmdPrinterName }} ({{ $pmdPrinterTarget }})</option>@endif @endforeach</select></label><input type="hidden" name="local_printer_target" id="pmd-local-printer-target" value=""></div></div>
        <div class="pmd-device-actions" style="margin-top:14px">@if(isset($formModel))<a class="pmd-device-action" href="{{ admin_url('cash_drawers/windows_connector/'.$formModel->drawer_id) }}">Download connector</a>@endif<button type="button" class="pmd-device-action" data-request="onCheckAgentBridge" data-request-form="#pmd-restaurant-profile-form">Check agent</button><button type="button" class="pmd-device-action" data-request="onLoadLocalPrinters" data-request-form="#pmd-restaurant-profile-form">Load printers</button><button type="button" class="pmd-device-action" data-request="onApplyLocalPrinter" data-request-form="#pmd-restaurant-profile-form">Use selected printer</button><button type="button" class="pmd-device-action" data-request="onTestConnection" data-request-form="#pmd-restaurant-profile-form">Test drawer</button><button type="button" class="pmd-device-action" data-request="onDiagnoseDrawer" data-request-form="#pmd-restaurant-profile-form">Diagnose</button><button type="button" class="pmd-device-action" data-request="onTestPrintLocal" data-request-form="#pmd-restaurant-profile-form">Test print</button><button type="button" class="pmd-device-action pmd-device-action--primary" data-request="onOpenDrawer" data-request-form="#pmd-restaurant-profile-form">Open drawer</button></div>
    </div></div></section>
    <section class="pmd-profile-section pmd-profile-section--violet"><div class="pmd-profile-card"><div class="pmd-profile-card__header"><div class="pmd-profile-section-icon"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"></circle><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.4-2.4 1a8 8 0 0 0-1.7-1L14.5 3h-5l-.4 3.1a8 8 0 0 0-1.7 1l-2.4-1-2 3.4L5.1 11a7 7 0 0 0 0 2L3 14.5l2 3.4 2.4-1a8 8 0 0 0 1.7 1l.4 3.1h5l.4-3.1a8 8 0 0 0 1.7-1l2.4 1 2-3.4-2.1-1.5a7 7 0 0 0 .1-1Z"></path></svg></div><div><h2>Technical connection</h2><p>Advanced hardware fields remain canonical.</p></div></div><div class="pmd-profile-card__body"><div class="pmd-profile-grid pmd-profile-grid--2 pmd-device-native-form">@foreach(['connection_type','device_path','esc_pos_command','voltage','network_ip','network_port','serial_port','serial_baud_rate','usb_vendor_id','usb_product_id','pos_device_id'] as $pmdName) @include('admin::pmddevices._v2_field',['pmdFormWidget'=>$pmdFormWidget,'pmdFieldName'=>$pmdName]) @endforeach</div></div></div></section>
    <div class="pmd-profile-bottom-save"><button type="button" class="pmd-profile-bottom-save__button" data-request="onSave" data-request-form="#pmd-restaurant-profile-form" data-request-flash><svg viewBox="0 0 24 24"><path d="M20 6 9 17l-5-5"></path></svg><span>Save changes</span></button></div>
    {!! form_close() !!}
</div>
<script>(function(){var s=document.getElementById('pmd-local-printer-name'),t=document.getElementById('pmd-local-printer-target');if(!s||!t)return;function sync(){var o=s.options[s.selectedIndex];t.value=o?(o.getAttribute('data-target')||o.value||''):'';}s.addEventListener('change',sync);sync();})();</script>
