"use client"

import { ThemeActionBoundary } from "@/components/themes/shared/ThemeActionBoundary"
import { KazenJapaneseBridgeTheme } from "@/components/themes/kazen-japanese"
import { PaymentModal } from "@/features/customer-menu/checkout/CheckoutModalHost"
import { pmdBuildKazenParentCategories } from "@/features/customer-menu/data/menuCategories"
import type { MenuItem } from "@/lib/data"
import { createOpenOrderUpdateHandler, normalizeMenuLogoUrl } from "@/features/customer-menu/theme/themeRouteShared"

type VelvetTerracottaThemeRouteProps = any
type VelvetValetValues = { name?: string; licensePlate?: string; license_plate?: string; carModel?: string; car_make?: string }
const getVelvetErrorMessage = (error: unknown, fallback: string) => error instanceof Error ? error.message : fallback

type VelvetMenuLayoutMode = "accordion" | "tabs"
function normalizeVelvetMenuLayoutMode(value: unknown): VelvetMenuLayoutMode { const raw = String(value || "").trim().toLowerCase().replace(/[_\s-]+/g, "-"); return ["tabs", "tab", "tabbed", "classic", "normal", "list", "flat", "category-tabs", "categories-top", "top-categories", "category-tabs-full-item-list"].includes(raw) ? "tabs" : "accordion" }
function readVelvetMenuLayoutMode(...sources: any[]): VelvetMenuLayoutMode { const keys = ["kazen_menu_layout", "kazenMenuLayout", "menu_layout", "menuLayout", "food_display_style", "foodDisplayStyle", "category_display", "categoryDisplay"]; for (const source of sources) { if (!source || typeof source !== "object") continue; for (const key of keys) { const direct = source?.[key]; if (direct !== undefined && direct !== null && String(direct).trim()) return normalizeVelvetMenuLayoutMode(direct); const data = source?.data?.[key]; if (data !== undefined && data !== null && String(data).trim()) return normalizeVelvetMenuLayoutMode(data); const settings = source?.settings?.[key]; if (settings !== undefined && settings !== null && String(settings).trim()) return normalizeVelvetMenuLayoutMode(settings) } } return "tabs" }

export function VelvetTerracottaThemeRoute(props: VelvetTerracottaThemeRouteProps) {
  const { apiMenuItems = [], menuItems = [], menuData = [], allCategories = [], tableInfo, displayTableNumber, tableIdString, cmsSettings, merchantSettings, taxSettings, items = [], totalItems = 0, totalPrice = 0, lastInteractedItem, restaurantDisplayName, themeMenuActions, addToCart, handleFirstAdd, toast, apiClient, handleItemSelect, handleCartClick, shouldShowTableOrderAction, setPaymentModalInitialStep, sharedTableOrder, setPaymentModalPreferPersonalReview, setPaymentModalOpen, tableOrderActionCount, isPaymentModalOpen, activeExistingOrderId, activePendingSummary, activeSubmittedOrder, paymentModalInitialStep, paymentModalPreferPersonalReview, setToolbarPricingSnapshot, setSharedTableOrder, setLocalOpenOrder, setHasLocalOpenOrder } = props
  const handleOpenOrderUpdate = createOpenOrderUpdateHandler({ setSharedTableOrder, setLocalOpenOrder, setHasLocalOpenOrder })
  const velvetSrc = typeof window !== "undefined" ? `/themes/velvet-terracotta/?embedded=1&from=pmd&${window.location.search.replace(/^\?/, "")}` : "/themes/velvet-terracotta/?embedded=1&from=pmd"
  const sourceItems = apiMenuItems.length ? apiMenuItems : (menuItems.length ? menuItems : menuData)
  const bridgeCategories = pmdBuildKazenParentCategories(allCategories, sourceItems)
  const tableNumber = tableInfo?.table_no ?? tableInfo?.table_id ?? displayTableNumber ?? tableIdString ?? null
  const logoCandidates = [cmsSettings?.effectiveLogoUrl, cmsSettings?.logoUrl, cmsSettings?.logo_url, cmsSettings?.logo, cmsSettings?.restaurantLogoUrl, cmsSettings?.restaurant_logo, cmsSettings?.site_logo, cmsSettings?.header_logo, cmsSettings?.frontend_logo, cmsSettings?.business_logo, cmsSettings?.brand_logo, cmsSettings?.data?.effectiveLogoUrl, cmsSettings?.data?.logoUrl, cmsSettings?.data?.logo_url, cmsSettings?.data?.logo, cmsSettings?.data?.restaurant_logo, merchantSettings?.effectiveLogoUrl, merchantSettings?.logoUrl, merchantSettings?.logo_url, merchantSettings?.logo, merchantSettings?.restaurantLogoUrl, merchantSettings?.restaurant_logo, merchantSettings?.site_logo, merchantSettings?.header_logo, merchantSettings?.frontend_logo, merchantSettings?.business_logo, merchantSettings?.brand_logo, merchantSettings?.data?.effectiveLogoUrl, merchantSettings?.data?.logoUrl, merchantSettings?.data?.logo_url, merchantSettings?.data?.logo, merchantSettings?.data?.restaurant_logo]
  const logoUrl = normalizeMenuLogoUrl(logoCandidates.find((value: unknown) => String(value || "").trim()) || "")
  const menuLayout = readVelvetMenuLayoutMode(cmsSettings, merchantSettings, typeof window !== "undefined" ? (window as any).__PMD_THEME_SETTINGS : null, typeof window !== "undefined" ? (window as any).__PMD_ADMIN_THEME_SETTINGS : null)
  const handleAdd = (item: MenuItem, quantity = 1) => { let itemToAdd: MenuItem = { ...item }; if (taxSettings?.enabled && taxSettings?.percentage > 0 && taxSettings?.menuPrice === 0) { itemToAdd.price = Number(item.price || 0) / (1 + taxSettings.percentage / 100); if (itemToAdd.options) itemToAdd.options = itemToAdd.options.map((option: NonNullable<MenuItem["options"]>[number]) => ({ ...option, values: (option.values || []).map((value: NonNullable<NonNullable<MenuItem["options"]>[number]["values"]>[number]) => ({ ...value, price: Number(value.price || 0) / (1 + taxSettings.percentage / 100) })) })) }; const currentQuantity = items.find((cartItem: { item: MenuItem }) => cartItem.item.id === item.id)?.quantity || 0; addToCart(itemToAdd, quantity); if (currentQuantity === 0) handleFirstAdd(item) }
  const handleWaiter = async () => { const resolvedTableId = tableInfo?.table_id || tableInfo?.table_no || tableIdString || "delivery"; try { await apiClient.callWaiter(String(resolvedTableId), "."); toast({ title: "Waiter called", description: "The team has been notified." }) } catch (error: unknown) { toast({ title: "Waiter call failed", description: getVelvetErrorMessage(error, "Failed to call waiter."), variant: "destructive" }) } }
  const handleNote = async (rawNote = "") => { const resolvedTableId = tableInfo?.table_id || tableInfo?.table_no || tableIdString || "delivery"; const trimmedNote = String(rawNote || "").trim(); if (!trimmedNote) { props.setNoteModalOpen?.(true); return }; try { await apiClient.callTableNote(String(resolvedTableId), trimmedNote, new Date().toISOString()); toast({ title: "Note sent", description: "Your note was sent to the team." }) } catch (error: unknown) { toast({ title: "Note failed", description: getVelvetErrorMessage(error, "Failed to send note."), variant: "destructive" }) } }
  const handleValet = async (values: any = {}) => { const name = String(values?.name || "Guest").trim() || "Guest"; const licensePlate = String(values?.licensePlate || values?.license_plate || "Not provided").trim() || "Not provided"; const carModel = String(values?.carModel || values?.car_make || "Not provided").trim() || "Not provided"; try { await apiClient.createValetRequest({ name, license_plate: licensePlate, car_make: carModel, table_id: tableIdString || undefined, table_no: tableNumber ? String(tableNumber) : undefined, qr: tableInfo?.qr_code ? String(tableInfo.qr_code) : undefined }); toast({ title: "Valet requested", description: "Your valet request has been sent." }) } catch (error: unknown) { toast({ title: "Valet request failed", description: getVelvetErrorMessage(error, "Failed to submit valet request."), variant: "destructive" }) } }
  return <ThemeActionBoundary actions={themeMenuActions}><KazenJapaneseBridgeTheme src={velvetSrc} sourceItems={sourceItems} cartItems={items} totalItems={totalItems} totalPrice={totalPrice} lastInteractedItem={lastInteractedItem} categories={bridgeCategories} restaurantName={restaurantDisplayName} logoUrl={logoUrl} tableNumber={tableNumber} menuLayout={menuLayout} onAddItem={handleAdd} onOpenItem={(item: MenuItem) => handleItemSelect(item)} onCheckout={handleCartClick} onCallWaiter={handleWaiter} onOpenNote={handleNote} onOpenValet={handleValet} onTableOrder={() => { if (!shouldShowTableOrderAction) return; setPaymentModalInitialStep(sharedTableOrder?.status === "draft" ? "review" : sharedTableOrder?.status === "paid" ? "paid" : "submitted"); setPaymentModalPreferPersonalReview(false); setPaymentModalOpen(true) }} showTableOrder={shouldShowTableOrderAction} tableOrderCount={tableOrderActionCount}><PaymentModal isOpen={isPaymentModalOpen} onClose={() => { setPaymentModalOpen(false); setPaymentModalPreferPersonalReview(false) }} items={items} tableInfo={tableInfo} existingOrderId={activeExistingOrderId} pendingSummary={activePendingSummary} initialSubmittedOrder={activeSubmittedOrder} initialCheckoutStep={paymentModalInitialStep} preferPersonalReview={paymentModalPreferPersonalReview} checkoutVisualTheme="kazen_japanese" onCartPricingUpdate={setToolbarPricingSnapshot} onOpenOrderUpdate={handleOpenOrderUpdate} /></KazenJapaneseBridgeTheme></ThemeActionBoundary>
}
