<?php return array (
  'System\\Classes\\ExtensionManager' => 'app/system/classes/ExtensionManager.php',
  'System\\Classes\\BaseExtension' => 'app/system/classes/BaseExtension.php',
  'igniter\\api\\Extension' => 'extensions/igniter/api/Extension.php',
  'igniter\\broadcast\\Extension' => 'extensions/igniter/broadcast/Extension.php',
  'igniter\\debugbar\\Extension' => 'extensions/igniter/debugbar/Extension.php',
  'igniter\\payregister\\Extension' => 'extensions/igniter/payregister/Extension.php',
  'igniter\\socialite\\Extension' => 'extensions/igniter/socialite/Extension.php',
  'System\\Classes\\MailManager' => 'app/system/classes/MailManager.php',
  'Admin\\Models\\Payments_model' => 'app/admin/models/Payments_model.php',
  'System\\Traits\\CombinesAssets' => 'app/system/traits/CombinesAssets.php',
  'System\\Libraries\\Assets' => 'app/system/libraries/Assets.php',
  'System\\Classes\\ComponentManager' => 'app/system/classes/ComponentManager.php',
  'Main\\Classes\\ThemeManager' => 'app/main/classes/ThemeManager.php',
  'Main\\Classes\\Theme' => 'app/main/classes/Theme.php',
  'System\\Classes\\ComposerManager' => 'app/system/classes/ComposerManager.php',
  'System\\Traits\\ConfigMaker' => 'app/system/traits/ConfigMaker.php',
  'System\\Actions\\ModelAction' => 'app/system/actions/ModelAction.php',
  'Admin\\Classes\\BasePaymentGateway' => 'app/admin/classes/BasePaymentGateway.php',
  'Igniter\\PayRegister\\Traits\\PaymentHelpers' => 'extensions/igniter/payregister/traits/PaymentHelpers.php',
  'Igniter\\PayRegister\\Payments\\Stripe' => 'extensions/igniter/payregister/payments/Stripe.php',
  'Igniter\\PayRegister\\Payments\\PaypalExpress' => 'extensions/igniter/payregister/payments/PaypalExpress.php',
  'Igniter\\PayRegister\\Payments\\SumUp' => 'extensions/igniter/payregister/payments/SumUp.php',
  'Admin\\Classes\\WorldlineHostedCheckoutService' => 'app/admin/classes/WorldlineHostedCheckoutService.php',
);