<?php
namespace Admin\Controllers;
use Admin\Facades\AdminAuth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Schema;

class PmdWaiterFloorLiveV106 extends \Admin\Classes\AdminController
{
    protected $requiredPermissions = 'Admin.Dashboard';
    protected $cols = [];

    public function data(){ try { $this->ensureBridge(); return Response::json($this->payload()); } catch (\Throwable $e){ return $this->err($e); } }
    public function audit(){ try { $this->ensureBridge(); return Response::json(['ok'=>true,'version'=>'v106','enabled_tables_count'=>count($this->enabledTables()),'enabled_tables_preview'=>array_slice($this->enabledTables(),0,20),'enabled_menu_items_count'=>count($this->enabledMenus()),'enabled_menu_preview'=>array_slice($this->enabledMenus(),0,20),'detected'=>$this->detected(),'menus_columns'=>Schema::hasTable('menus')?$this->columns('menus'):[],'tables_columns'=>Schema::hasTable('tables')?$this->columns('tables'):[]]); } catch (\Throwable $e){ return $this->err($e); } }
    public function assign(){ try { $this->ensureBridge(); $apply=request()->get('apply')=='1'; $count=max(1,min(50,(int)request()->get('count',4))); $ids=$this->parseIds(request()->get('tables','')); $user=$this->userInfo(); $tables=$this->enabledTables(); if(!$ids) $ids=array_slice(array_map(fn($t)=>(int)$t['table_id'],$tables),0,$count); $selected=array_values(array_filter($tables,fn($t)=>in_array((int)$t['table_id'],$ids,true))); if($apply) foreach($selected as $t) $this->assignTable((int)$user['staff_id'],$t,$user); return Response::json(['ok'=>true,'version'=>'v106','mode'=>$apply?'APPLIED':'DRY_RUN','selected'=>$selected]); } catch (\Throwable $e){ return $this->err($e); } }
    public function merge(){ try { $this->ensureBridge(); $apply=request()->get('apply')=='1'; $p=(int)request()->get('primary'); $s=(int)request()->get('secondary'); if(!$p||!$s||$p===$s) return Response::json(['ok'=>false,'version'=>'v106','error'=>'primary and secondary table ids required'],422); if($apply){ DB::table('pmd_table_merges')->where('secondary_table_id',$s)->where('status','active')->update(['status'=>'inactive','updated_at'=>date('Y-m-d H:i:s')]); DB::table('pmd_table_merges')->insert(['primary_table_id'=>$p,'secondary_table_id'=>$s,'status'=>'active','staff_id'=>(int)$this->userInfo()['staff_id'],'notes'=>'Created from v106 floor merge','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')]); } return Response::json(['ok'=>true,'version'=>'v106','mode'=>$apply?'APPLIED':'DRY_RUN','primary'=>$p,'secondary'=>$s]); } catch (\Throwable $e){ return $this->err($e); } }
    public function resetTables(){ try { $this->ensureBridge(); $apply=request()->get('apply')=='1'; $confirm=request()->get('confirm'); $count=max(1,min(60,(int)request()->get('count',12))); if(!$apply||$confirm!=='REBUILD') return Response::json(['ok'=>true,'version'=>'v106','mode'=>'DRY_RUN','warning'=>'This disables current enabled tables and creates new clean enabled tables. It does NOT delete rows, to protect orders/reservations.','run'=>'/admin/pmd-waiter-floor-v106-reset-tables?apply=1&confirm=REBUILD&count='.$count]); $cols=$this->columns('tables'); DB::beginTransaction(); if(in_array('table_status',$cols,true)) DB::table('tables')->update(['table_status'=>0,'updated_at'=>date('Y-m-d H:i:s')]); $created=[]; for($i=1;$i<=$count;$i++){ $r=[]; if(in_array('table_no',$cols,true)) $r['table_no']=(string)$i; if(in_array('table_name',$cols,true)) $r['table_name']='Table '.$i; if(in_array('pos_table_label',$cols,true)) $r['pos_table_label']='Table '.$i; if(in_array('min_capacity',$cols,true)) $r['min_capacity']=1; if(in_array('max_capacity',$cols,true)) $r['max_capacity']=4; if(in_array('extra_capacity',$cols,true)) $r['extra_capacity']=0; if(in_array('priority',$cols,true)) $r['priority']=$i; if(in_array('is_joinable',$cols,true)) $r['is_joinable']=1; if(in_array('table_status',$cols,true)) $r['table_status']=1; if(in_array('created_at',$cols,true)) $r['created_at']=date('Y-m-d H:i:s'); if(in_array('updated_at',$cols,true)) $r['updated_at']=date('Y-m-d H:i:s'); $created[]=DB::table('tables')->insertGetId($r); } DB::commit(); return Response::json(['ok'=>true,'version'=>'v106','created_table_ids'=>$created]); } catch (\Throwable $e){ try{DB::rollBack();}catch(\Throwable $x){} return $this->err($e); } }

    protected function payload(){ $user=$this->userInfo(); $assigned=$this->assignedIds($user); $merges=$this->mergeMap(); $tables=[]; foreach($this->enabledTables() as $t){ $id=(int)$t['table_id']; $open=$this->openOrders($id,$t); $ready=$this->readyItems($id,$t); $due=$this->due($id,$t); $res=$this->reservation($id); $att=$this->attention($id); $isAssigned=in_array($id,$assigned,true); $merged=$merges[$id]??null; $status='free'; if($merged)$status='merged'; elseif($att['count']>0)$status='attention'; elseif($ready>0)$status='ready'; elseif($due>0)$status='unpaid'; elseif($open>0)$status='open'; elseif($res['count']>0)$status='reserved'; elseif($isAssigned)$status='assigned'; $tables[]=array_merge($t,['assigned'=>$isAssigned,'merged'=>$merged,'floor_status'=>$status,'open_order_count'=>$open,'ready_count'=>$ready,'due_amount'=>$due,'due_label'=>$this->money($due),'reservation'=>$res,'attention'=>$att,'edit_url'=>'/admin/tables/edit/'.$id]); }
        $mine=array_values(array_filter($tables,fn($t)=>$t['assigned'])); $ready=array_sum(array_map(fn($t)=>(int)$t['ready_count'],$mine)); $open=array_sum(array_map(fn($t)=>(int)$t['open_order_count'],$mine)); $att=array_sum(array_map(fn($t)=>(int)$t['attention']['count'],$mine)); $due=array_sum(array_map(fn($t)=>(float)$t['due_amount'],$mine)); return ['ok'=>true,'version'=>'v106','mode'=>'LIVE_ENABLED_TABLES_REAL_MENUS','generated_at'=>date('c'),'user'=>$user,'detected'=>$this->detected(),'detected_tables'=>$this->detected(),'tables'=>$tables,'assigned_tables'=>$mine,'assigned_table_ids'=>array_values($assigned),'menu_items'=>$this->enabledMenus(),'menu_source'=>'/admin/menus -> menus table where menu_status=1','counts'=>['tables'=>count($tables),'assigned_tables'=>count($mine),'menu_items'=>count($this->enabledMenus())],'metrics'=>['my_tables'=>['label'=>'MY TABLES','value'=>$this->compactTables($mine),'sub'=>count($mine).' assigned','count'=>count($mine),'total'=>count($tables)],'ready_to_serve'=>['label'=>'READY TO SERVE','value'=>(string)$ready,'sub'=>'items from kitchen','count'=>$ready,'total'=>$ready],'active_orders'=>['label'=>'ACTIVE ORDERS','value'=>(string)$open,'sub'=>'my open orders','count'=>$open,'total'=>$open],'needs_attention'=>['label'=>'NEEDS ATTENTION','value'=>(string)$att,'sub'=>'calls / notes / allergies','count'=>$att,'total'=>$att],'checks_to_close'=>['label'=>'CHECKS TO CLOSE','value'=>$this->money($due),'sub'=>$this->pendingPayments($mine).' payments pending','count'=>$this->pendingPayments($mine),'total'=>$due]]]; }

    protected function enabledTables(){ if(!Schema::hasTable('tables')) return []; $c=$this->columns('tables'); $q=DB::table('tables'); if(in_array('table_status',$c,true)) $q->where('table_status',1); if(in_array('priority',$c,true)) $q->orderBy('priority'); elseif(in_array('table_no',$c,true)) $q->orderBy('table_no'); else $q->orderBy('table_id'); $out=[]; foreach($q->limit(250)->get() as $row){ $r=(array)$row; $id=(int)($r['table_id']??$r['id']??0); if(!$id) continue; $no=trim((string)($r['table_no']??$id)); $label=trim((string)($r['pos_table_label']??$r['table_name']??'')); if($label==='') $label='Table '.$no; if(preg_match('/cashier|delivery|takeaway|pickup|counter/i',strtolower($label))) continue; $out[]=['table_id'=>$id,'id'=>$id,'number'=>$no,'label'=>$label,'min_capacity'=>(int)($r['min_capacity']??1),'max_capacity'=>(int)($r['max_capacity']??4),'is_joinable'=>(int)($r['is_joinable']??0),'priority'=>(int)($r['priority']??$id),'enabled'=>true]; } return $out; }
    protected function enabledMenus(){ if(!Schema::hasTable('menus')) return []; $c=$this->columns('menus'); $q=DB::table('menus'); if(in_array('menu_status',$c,true)) $q->where('menu_status',1); if(in_array('is_stock_out',$c,true)) $q->where(fn($qq)=>$qq->whereNull('is_stock_out')->orWhere('is_stock_out',0)); if(in_array('menu_priority',$c,true)) $q->orderBy('menu_priority'); elseif(in_array('menu_name',$c,true)) $q->orderBy('menu_name'); $out=[]; foreach($q->limit(500)->get() as $row){ $r=(array)$row; $id=(int)($r['menu_id']??$r['id']??0); $name=trim((string)($r['menu_name']??$r['name']??'')); if(!$id||$name==='') continue; if(preg_match('/PMD\s+(Ready|Test)|fake|sample/i',$name)) continue; $price=(float)($r['menu_price']??0); if($price<=0) $price=$this->menuPrice($id,$price); $out[]=['id'=>$id,'menu_id'=>$id,'name'=>$name,'price'=>$price,'price_label'=>$this->money($price),'category_id'=>$r['menu_category_id']??null,'prep_time_minutes'=>$r['prep_time_minutes']??null,'edit_url'=>'/admin/menus/edit/'.$id,'source'=>'menus']; } return $out; }
    protected function menuPrice($id,$fallback){ if(!Schema::hasTable('menu_prices')) return $fallback; $c=$this->columns('menu_prices'); if(!in_array('menu_id',$c,true)||!in_array('price',$c,true)) return $fallback; try{ $q=DB::table('menu_prices')->where('menu_id',$id); if(in_array('is_active',$c,true)) $q->where('is_active',1); if(in_array('priority',$c,true)) $q->orderBy('priority'); $row=$q->first(); return $row?(float)((array)$row)['price']:$fallback; } catch (\Throwable $e){ return $fallback; } }

    protected function ordersFor($id,$t){ $q=DB::table('orders'); $c=$this->columns('orders'); $no=(string)($t['number']??$id); $label=(string)($t['label']??('Table '.$no)); return $q->where(function($qq) use($c,$id,$no,$label){ if(in_array('table_id',$c,true)) $qq->orWhere('table_id',$id); if(in_array('location_table_id',$c,true)) $qq->orWhere('location_table_id',$id); if(in_array('table_no',$c,true)) $qq->orWhere('table_no',$no); if(in_array('table_number',$c,true)) $qq->orWhere('table_number',$no); if(in_array('order_type',$c,true)) $qq->orWhere('order_type',(string)$id)->orWhere('order_type',$no)->orWhere('order_type','Table '.$no)->orWhere('order_type',$label); }); }
    protected function openOrders($id,$t){ if(!Schema::hasTable('orders')) return 0; try{ $q=$this->ordersFor($id,$t); $c=$this->columns('orders'); if(in_array('processed',$c,true)) $q->where('processed',0); return (int)$q->count(); } catch (\Throwable $e){ return 0; } }
    protected function due($id,$t){ if(!Schema::hasTable('orders')) return 0; $c=$this->columns('orders'); $total=$this->pick($c,['order_total','total','total_amount','grand_total']); if(!$total) return 0; try{ $q=$this->ordersFor($id,$t); if(in_array('processed',$c,true)) $q->where('processed',0); return (float)$q->sum($total); } catch (\Throwable $e){ return 0; } }
    protected function readyItems($id,$t){ if(!Schema::hasTable('orders')||!Schema::hasTable('order_menus')) return 0; try{ $oc=$this->columns('orders'); $mc=$this->columns('order_menus'); $pk=$this->pick($oc,['order_id','id']); $fk=$this->pick($mc,['order_id']); if(!$pk||!$fk) return 0; $ids=$this->ordersFor($id,$t)->pluck($pk)->all(); if(!$ids) return 0; $q=DB::table('order_menus')->whereIn($fk,$ids); $status=$this->pick($mc,['kds_status','item_status','status','status_name','order_menu_status','cooking_status']); $bool=$this->pick($mc,['is_ready','ready','completed','is_completed']); if($status) $q->where(fn($qq)=>$qq->where($status,'like','%ready%')->orWhere($status,'like','%complete%')->orWhere($status,'like','%done%')->orWhere($status,'like','%serve%')); elseif($bool) $q->where($bool,1); else return 0; $served=$this->pick($mc,['served','is_served']); if($served) $q->where(fn($qq)=>$qq->whereNull($served)->orWhere($served,0)); return (int)$q->count(); } catch (\Throwable $e){ return 0; } }
    protected function reservation($id){ $info=['count'=>0,'next_time'=>null,'ids'=>[]]; if(!Schema::hasTable('reservations')) return $info; try{ $ids=[]; if(Schema::hasTable('reservation_tables')) $ids=DB::table('reservation_tables')->where('table_id',$id)->pluck('reservation_id')->all(); $c=$this->columns('reservations'); $q=DB::table('reservations')->where(function($qq) use($id,$ids,$c){ if(in_array('table_id',$c,true)) $qq->orWhere('table_id',$id); if($ids) $qq->orWhereIn('reservation_id',$ids); }); if(in_array('reserve_date',$c,true)) $q->where('reserve_date',date('Y-m-d')); if(in_array('status_id',$c,true)) $q->where('status_id','>=',1); $rows=$q->limit(20)->get(); $times=[]; $res=[]; foreach($rows as $row){ $r=(array)$row; if(!empty($r['reserve_time'])) $times[]=(string)$r['reserve_time']; if(!empty($r['reservation_id'])) $res[]=(int)$r['reservation_id']; } sort($times); return ['count'=>count($rows),'next_time'=>$times[0]??null,'ids'=>$res]; } catch (\Throwable $e){ return $info; } }
    protected function attention($id){ $count=0; $types=[]; if(Schema::hasTable('notifications')){ try{ $c=$this->columns('notifications'); if(in_array('table_id',$c,true)){ $q=DB::table('notifications')->where('table_id',$id); if(in_array('status',$c,true)) $q->whereIn('status',['new','in_progress']); foreach($q->limit(20)->get() as $row){ $r=(array)$row; $count++; if(!empty($r['type'])) $types[]=$r['type']; } } } catch (\Throwable $e){} } foreach(['table_notes','ti_table_notes'] as $tn){ if(Schema::hasTable($tn)){ try{ $c=$this->columns($tn); if(in_array('table_id',$c,true)){ $q=DB::table($tn)->where('table_id',$id); if(in_array('status',$c,true)) $q->whereIn('status',['new']); $n=(int)$q->count(); if($n){ $count+=$n; $types[]='note'; } } } catch (\Throwable $e){} } } return ['count'=>$count,'types'=>array_values(array_unique($types))]; }

    protected function ensureBridge(){ if(!Schema::hasTable('pmd_waiter_table_assignments')) Schema::create('pmd_waiter_table_assignments',function($t){ $t->increments('id'); $t->integer('staff_id')->unsigned()->index(); $t->integer('table_id')->unsigned()->index(); $t->integer('location_id')->unsigned()->nullable()->index(); $t->string('section_name')->nullable(); $t->boolean('is_active')->default(1)->index(); $t->integer('assigned_by')->unsigned()->nullable(); $t->text('notes')->nullable(); $t->timestamps(); }); if(!Schema::hasTable('pmd_table_merges')) Schema::create('pmd_table_merges',function($t){ $t->increments('id'); $t->integer('primary_table_id')->index(); $t->integer('secondary_table_id')->index(); $t->string('status')->default('active')->index(); $t->integer('staff_id')->nullable()->index(); $t->text('notes')->nullable(); $t->timestamps(); }); }
    protected function assignTable($staffId,$table,$user){ if(!$staffId) return; $exists=DB::table('pmd_waiter_table_assignments')->where('staff_id',$staffId)->where('table_id',(int)$table['table_id'])->where('is_active',1)->exists(); if($exists) return; DB::table('pmd_waiter_table_assignments')->insert(['staff_id'=>$staffId,'table_id'=>(int)$table['table_id'],'location_id'=>$table['location_id']??null,'section_name'=>'Floor section','is_active'=>1,'assigned_by'=>$user['id']??null,'notes'=>'Assigned from v106','created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')]); }
    protected function mergeMap(){ $out=[]; if(!Schema::hasTable('pmd_table_merges')) return $out; try{ foreach(DB::table('pmd_table_merges')->where('status','active')->get() as $row){ $r=(array)$row; $out[(int)$r['secondary_table_id']]=['primary_table_id'=>(int)$r['primary_table_id'],'status'=>'active']; } } catch (\Throwable $e){} return $out; }
    protected function userInfo(){ $user=null; try{ $user=AdminAuth::getUser(); } catch (\Throwable $e){ try{ $user=AdminAuth::user(); }catch(\Throwable $e2){} } $out=['id'=>null,'staff_id'=>null,'username'=>'','email'=>'']; if($user){ $a=is_object($user)&&method_exists($user,'getAttributes')?$user->getAttributes():(array)$user; $out['id']=isset($a['id'])?(int)$a['id']:(isset($a['user_id'])?(int)$a['user_id']:null); foreach(['staff_id','staffId'] as $k) if(isset($a[$k])&&is_numeric($a[$k])) $out['staff_id']=(int)$a[$k]; foreach(['username','name','login','staff_name'] as $k) if(!empty($a[$k])){ $out['username']=(string)$a[$k]; break; } foreach(['email','staff_email'] as $k) if(!empty($a[$k])){ $out['email']=(string)$a[$k]; break; } } if(!$out['staff_id']) $out['staff_id']=$out['id'] ?: 1; return $out; }
    protected function assignedIds($user){ if(!Schema::hasTable('pmd_waiter_table_assignments')) return []; try{ return array_values(array_unique(array_map('intval',DB::table('pmd_waiter_table_assignments')->where('staff_id',(int)$user['staff_id'])->where('is_active',1)->pluck('table_id')->all()))); } catch (\Throwable $e){ return []; } }
    protected function columns($table){ if(isset($this->cols[$table])) return $this->cols[$table]; try{ $rows=DB::select('DESCRIBE `'.str_replace('`','``',$table).'`'); $out=[]; foreach($rows as $row){ $r=(array)$row; if(!empty($r['Field'])) $out[]=$r['Field']; } return $this->cols[$table]=$out; } catch (\Throwable $e){ return $this->cols[$table]=[]; } }
    protected function pick($cols,$names){ foreach($names as $n) if(in_array($n,$cols,true)) return $n; return null; }
    protected function parseIds($s){ $out=[]; foreach(preg_split('/[,\s]+/',(string)$s) as $p) if(is_numeric($p)) $out[]=(int)$p; return array_values(array_unique($out)); }
    protected function pendingPayments($tables){ $n=0; foreach($tables as $t) if((float)$t['due_amount']>0) $n++; return $n; }
    protected function compactTables($tables){ if(!$tables) return '—'; $p=[]; foreach(array_slice($tables,0,3) as $t) $p[]='T'.$t['number']; return implode('/',$p).(count($tables)>3?'/…':''); }
    protected function detected(){ return ['tables'=>Schema::hasTable('tables')?'tables':null,'menus'=>Schema::hasTable('menus')?'menus':null,'orders'=>Schema::hasTable('orders')?'orders':null,'order_menus'=>Schema::hasTable('order_menus')?'order_menus':null,'reservations'=>Schema::hasTable('reservations')?'reservations':null,'reservation_tables'=>Schema::hasTable('reservation_tables')?'reservation_tables':null,'notifications'=>Schema::hasTable('notifications')?'notifications':null,'table_notes'=>Schema::hasTable('table_notes')?'table_notes':(Schema::hasTable('ti_table_notes')?'ti_table_notes':null),'assignments'=>Schema::hasTable('pmd_waiter_table_assignments')?'pmd_waiter_table_assignments':null,'merges'=>Schema::hasTable('pmd_table_merges')?'pmd_table_merges':null]; }
    protected function money($v){ return '€'.number_format((float)$v,2); }
    protected function err($e){ return Response::json(['ok'=>false,'version'=>'v106','error'=>$e->getMessage(),'file'=>basename($e->getFile()),'line'=>$e->getLine(),'detected'=>$this->detected()],500); }
}
