// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/general" | "/admin/menu" | "/admin/menu/[id]" | "/admin/merchant" | "/admin/payment-providers" | "/admin/payments" | "/checkout" | "/dashboard" | "/menu" | "/menu/table-[table_id]" | "/order-placed" | "/payment/sumup/complete" | "/table/[table_id]" | "/table/[table_id]/menu" | "/table/[table_id]/valet" | "/themes/kazen-japanese" | "/themes/velvet-terracotta" | "/valet" | "/worldline-return" | "/worldline-test"
type AppRouteHandlerRoutes = "/api/debug/client-log" | "/api/orders/confirm" | "/api/payment-methods" | "/api/payments/capture-paypal-order" | "/api/payments/create-intent" | "/api/payments/create-paypal-order" | "/api/payments/process-apple-pay" | "/api/payments/process-cash" | "/api/payments/process-google-pay" | "/api/payments/validate-apple-pay" | "/settings"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = "/[[...path]]" | "/api/media/[[...path]]" | "/api/v1/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[[...path]]": { "path"?: string[]; }
  "/admin": {}
  "/admin/general": {}
  "/admin/menu": {}
  "/admin/menu/[id]": { "id": string; }
  "/admin/merchant": {}
  "/admin/payment-providers": {}
  "/admin/payments": {}
  "/api/debug/client-log": {}
  "/api/media/[[...path]]": { "path"?: string[]; }
  "/api/orders/confirm": {}
  "/api/payment-methods": {}
  "/api/payments/capture-paypal-order": {}
  "/api/payments/create-intent": {}
  "/api/payments/create-paypal-order": {}
  "/api/payments/process-apple-pay": {}
  "/api/payments/process-cash": {}
  "/api/payments/process-google-pay": {}
  "/api/payments/validate-apple-pay": {}
  "/api/v1/[[...path]]": { "path"?: string[]; }
  "/checkout": {}
  "/dashboard": {}
  "/menu": {}
  "/menu/table-[table_id]": {}
  "/order-placed": {}
  "/payment/sumup/complete": {}
  "/settings": {}
  "/table/[table_id]": { "table_id": string; }
  "/table/[table_id]/menu": { "table_id": string; }
  "/table/[table_id]/valet": { "table_id": string; }
  "/themes/kazen-japanese": {}
  "/themes/velvet-terracotta": {}
  "/valet": {}
  "/worldline-return": {}
  "/worldline-test": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
