@include('admin::pmddevices._v2_boot')
@php
$pmdFormWidget = $this->widgets['form'] ?? null; try { if ($pmdFormWidget) $pmdFormWidget->render(['useContainer'=>false]); } catch (\Throwable $e) {}
$pmdDeviceCode = strtolower((string)(optional($formModel->devices ?? null)->code ?? ''));
@endphp
<div id="pmd-restaurant-profile" data-pmd-restaurant-profile data-pmd-device-settings-v2="pos-config-edit">
    @include('admin::pmddevices._v2_header',['pmdSuiteTitle'=>'Edit POS integration','pmdSuiteBackUrl'=>admin_url('pos_configs'),'pmdSuiteSave'=>true,'pmdSuiteDelete'=>true])
    {!! form_open(['id'=>'pmd-restaurant-profile-form','role'=>'form','method'=>'PATCH']) !!}
    <section class="pmd-profile-section pmd-profile-section--cyan"><div class="pmd-profile-card"><div class="pmd-profile-card__header"><div class="pmd-profile-section-icon"><svg viewBox="0 0 24 24"><path d="M5 6h14M5 12h14M5 18h14"></path></svg></div><div><h2>Integration credentials</h2><p>Provider identity, endpoint and canonical credentials.</p></div></div><div class="pmd-profile-card__body"><div class="pmd-profile-grid pmd-profile-grid--2 pmd-device-native-form">@foreach(['devices','url','username','password','access_token','id_application','sumup_affiliate_key','sumup_reader_id','sumup_pairing_code','sumup_pairing_state','sumup_reader_label','sumup_pos_migration_notice'] as $pmdName) @include('admin::pmddevices._v2_field',['pmdFormWidget'=>$pmdFormWidget,'pmdFieldName'=>$pmdName]) @endforeach</div></div></div></section>
    <section class="pmd-profile-section pmd-profile-section--violet"><div class="pmd-profile-card"><div class="pmd-profile-card__header"><div class="pmd-profile-section-icon"><svg viewBox="0 0 24 24"><path d="M4 12h16M12 4v16"></path></svg></div><div><h2>Integration tools</h2><p>Existing test, sync and webhook handlers stay on the canonical controller.</p></div></div><div class="pmd-profile-card__body"><div class="pmd-device-actions"><button type="button" class="pmd-device-action" data-request="onTestIntegration" data-request-form="#pmd-restaurant-profile-form">Test integration</button><button type="button" class="pmd-device-action" data-request="onSyncMenu" data-request-form="#pmd-restaurant-profile-form">Sync menu</button><button type="button" class="pmd-device-action" data-request="onRegisterWebhook" data-request-form="#pmd-restaurant-profile-form">Register webhook</button>@if($pmdDeviceCode==='ready2order')<button type="button" id="pmd-device-r2o-sync" class="pmd-device-action pmd-device-action--primary">Sync Ready2Order tables</button>@endif</div><pre id="pmd-pos-action-result" class="pmd-device-result" hidden></pre></div></div></section>
    <div class="pmd-profile-bottom-save"><button type="button" class="pmd-profile-bottom-save__button" data-request="onSave" data-request-form="#pmd-restaurant-profile-form" data-request-flash><svg viewBox="0 0 24 24"><path d="M20 6 9 17l-5-5"></path></svg><span>Save changes</span></button></div>{!! form_close() !!}
</div>
@if($pmdDeviceCode==='ready2order')
<div id="pmd-device-r2o-overlay" aria-hidden="true"><div id="pmd-device-r2o-modal"><div style="display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px"><div><strong style="font-size:18px;color:#17231f">Ready2Order table sync</strong><div style="margin-top:4px;color:#71817d;font-size:11px">Canonical existing sync endpoint result</div></div><button type="button" id="pmd-device-r2o-close" class="pmd-device-action">Close</button></div><pre id="pmd-device-r2o-output" class="pmd-device-result" style="margin:0"></pre></div></div>
<script>(function(){var b=document.getElementById('pmd-device-r2o-sync'),o=document.getElementById('pmd-device-r2o-overlay'),c=document.getElementById('pmd-device-r2o-close'),out=document.getElementById('pmd-device-r2o-output');if(!b||!o||!out)return;function close(){o.classList.remove('is-open');o.setAttribute('aria-hidden','true');}if(c)c.addEventListener('click',close);o.addEventListener('click',function(e){if(e.target===o)close();});b.addEventListener('click',function(){b.disabled=true;out.textContent='Syncing...';o.classList.add('is-open');o.setAttribute('aria-hidden','false');fetch("{{ url('r2o_sync_tables_ajax.php') }}",{method:'GET',headers:{'X-Requested-With':'XMLHttpRequest','Accept':'application/json'},credentials:'same-origin'}).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(function(d){out.textContent=JSON.stringify(d,null,2);}).catch(function(e){out.textContent=String(e&&e.message?e.message:e);}).finally(function(){b.disabled=false;});});})();</script>
@endif
