#!/usr/bin/env python3
from pathlib import Path
import sys

MARKER = "PMD_SUMUP_PUBLIC_KEY_VALIDATION_R1_4_7"


def fail(message: str) -> None:
    raise SystemExit("ERROR: " + message)


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        fail(f"{label} expected once, found {count}")
    return text.replace(old, new, 1)


def patch_service(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    if MARKER in text:
        return
    if "PMD_SUMUP_SWIFT_CONFIG_R5" not in text:
        fail("live SumUp Swift R5 marker missing")

    old_configured = "                'configured' => str_starts_with($publicKey, 'sup_pk_'),\n"
    new_configured = "                'configured' => $this->isUsableSwiftPublicKey($publicKey), // PMD_SUMUP_PUBLIC_KEY_VALIDATION_R1_4_7\n"
    text = replace_once(text, old_configured, new_configured, "walletSettings Swift configured flag")

    old_validation = """            if ($walletPublicKey !== '' && !preg_match('/^sup_pk_[A-Za-z0-9._-]{6,500}$/', $walletPublicKey)) {
                throw new RuntimeException('SumUp Wallet Public Key must start with sup_pk_. Do not paste the secret sup_sk_ API key here.');
            }
"""
    new_validation = """            if ($walletPublicKey !== '' && !$this->isUsableSwiftPublicKey($walletPublicKey)) {
                throw new RuntimeException('SumUp Wallet Public Key is invalid. Paste the real public merchant key generated by SumUp (sup_pk_...). Placeholder/example values are rejected. Never paste a sup_sk_ secret key here.');
            }
"""
    text = replace_once(text, old_validation, new_validation, "saveWalletSettings public-key validation")

    old_swift_guard = """        if (!str_starts_with($publicKey, 'sup_pk_')) {
            throw new RuntimeException('SumUp Wallet Public Key is missing. Copy the sup_pk_ key from SumUp Dashboard → Settings → For Developers → Toolkit → API Keys into PayMyDine.');
        }
"""
    new_swift_guard = """        if (!$this->isUsableSwiftPublicKey($publicKey)) {
            throw new RuntimeException('SumUp Wallet Public Key is missing or invalid. Copy the real sup_pk_ public merchant key from SumUp Dashboard → Settings → For Developers → Toolkit → API Keys into PayMyDine. Placeholder/example values cannot authorize Swift Checkout.');
        }
"""
    text = replace_once(text, old_swift_guard, new_swift_guard, "swiftCheckoutConfig public-key guard")

    anchor = "    protected function activeConfig(): array\n"
    helper = r'''    protected function isUsableSwiftPublicKey(string $publicKey): bool
    {
        // PMD_SUMUP_PUBLIC_KEY_VALIDATION_R1_4_7
        // Swift Checkout calls SumUp merchant-profile with this browser-safe
        // public merchant key. Prefix-only checks accepted documentation
        // placeholders such as sup_pk_PASTE_YOUR_REAL_PUBLIC_KEY_HERE and then
        // exposed a broken Apple Pay button which failed with HTTP 401.
        $publicKey = trim($publicKey);
        if (!preg_match('/^sup_pk_[A-Za-z0-9._-]{12,500}$/', $publicKey)) {
            return false;
        }

        $upper = strtoupper($publicKey);
        foreach (['PASTE_', 'PLACEHOLDER', 'EXAMPLE_', '_HERE'] as $forbidden) {
            if (str_contains($upper, $forbidden)) {
                return false;
            }
        }

        return true;
    }

'''
    text = replace_once(text, anchor, helper + anchor, "SumUp service helper insertion")
    path.write_text(text, encoding="utf-8")


def patch_bridge(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    if MARKER in text:
        return
    if "PMD_SUMUP_WALLET_CATALOGUE_SYNC_R1_4_6" not in text:
        fail("R1.4.6 wallet catalogue marker missing")

    old = "        $applePayReady = str_starts_with($walletPublicKey, 'sup_pk_');\n"
    new = """        // PMD_SUMUP_PUBLIC_KEY_VALIDATION_R1_4_7
        $walletKeyUpper = strtoupper($walletPublicKey);
        $applePayReady = preg_match('/^sup_pk_[A-Za-z0-9._-]{12,500}$/', $walletPublicKey) === 1
            && !str_contains($walletKeyUpper, 'PASTE_')
            && !str_contains($walletKeyUpper, 'PLACEHOLDER')
            && !str_contains($walletKeyUpper, 'EXAMPLE_')
            && !str_contains($walletKeyUpper, '_HERE');
"""
    text = replace_once(text, old, new, "R1.4.6 Apple Pay readiness")
    path.write_text(text, encoding="utf-8")


def main() -> None:
    if len(sys.argv) != 3:
        fail("usage: patch-pmd-sumup-public-key-validation-r1-4-7.py <SumupOnlineCheckoutService.php> <SumupPaymentRuntimeBridge.php>")

    service = Path(sys.argv[1]).resolve()
    bridge = Path(sys.argv[2]).resolve()
    for target in [service, bridge]:
        if not target.is_file():
            fail("target not found: " + str(target))

    patch_service(service)
    patch_bridge(bridge)

    if MARKER not in service.read_text(encoding="utf-8"):
        fail("service validation marker missing")
    if MARKER not in bridge.read_text(encoding="utf-8"):
        fail("bridge validation marker missing")

    print("PMD_SUMUP_PUBLIC_KEY_VALIDATION_R1_4_7=OK")
    print("PLACEHOLDER_PUBLIC_KEYS=REJECTED")
    print("SWIFT_CONFIG=FAIL_CLOSED_BEFORE_SUMUP_401")
    print("APPLE_PAY_CATALOGUE=REAL_SUP_PK_ONLY")
    print("GOOGLE_PAY_CATALOGUE=REAL_SUP_PK_PLUS_GOOGLE_METADATA")


if __name__ == "__main__":
    main()
