<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Super Admin Login | PayMyDine</title>
<style>
*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:#f8fbfd;font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#16312a}.card{width:min(430px,calc(100vw - 28px));background:#fff;border:1px solid #dfe9e5;border-radius:24px;padding:28px;box-shadow:0 18px 50px rgba(18,61,50,.1)}.brand{display:flex;align-items:center;gap:12px;margin-bottom:26px}.brand img{width:42px;height:42px}.brand strong{display:block;font-size:20px}.brand span{font-size:11px;color:#6f827b}.field{display:grid;gap:7px;margin-bottom:14px}.field label{font-size:11px;font-weight:800}.field input{border:1px solid #d8e5e0;border-radius:12px;padding:12px}.btn{width:100%;border:0;background:#123d32;color:#fff;border-radius:12px;padding:12px;font-weight:800;cursor:pointer}.note{margin:18px 0 0;color:#6f827b;font-size:11px;text-align:center}.error{background:#fff1f0;border:1px solid #fecdca;color:#b42318;border-radius:12px;padding:10px 12px;margin-bottom:14px;font-size:12px}
</style>
</head>
<body><div class="card"><div class="brand"><img src="/app/admin/assets/images/pmd-brand-mark.svg" alt="PMD"><div><strong>Pay My Dine</strong><span>Super Admin Control Plane</span></div></div><h1 style="font-size:26px;margin:0 0 6px">Welcome back</h1><p style="margin:0 0 22px;color:#6f827b;font-size:13px">Sign in to manage restaurants, tenant health and platform settings.</p>@if($errors->any())<div class="error">{{ $errors->first() }}</div>@endif<form method="POST" action="/superadmin/sign">@csrf<div class="field"><label>Username</label><input name="username" autocomplete="username" required autofocus></div><div class="field"><label>Password</label><input type="password" name="password" autocomplete="current-password" required></div><button class="btn" type="submit">Sign in</button></form><p class="note">Central platform access. Tenant databases are not selected on this page.</p></div></body></html>
