@extends('admin::superadmin_r2.layout')
@section('title','Restaurants')
@section('page_title','Restaurants')
@section('page_subtitle','Create, review and manage PayMyDine tenants')
@section('content')
<div class="hero"><div><h2>Restaurants</h2><p>Central tenant registry and onboarding.</p></div></div>
<div class="grid2">
<div class="card"><div class="card-head"><div><h3>Restaurant registry</h3><p>Search by name, domain, database or email.</p></div></div><form class="filters" method="GET" action="/superadmin/new"><input name="q" value="{{ $search }}" placeholder="Search restaurants"><select name="status"><option value="">All statuses</option><option value="active" {{ $status==='active'?'selected':'' }}>Active</option><option value="disabled" {{ $status==='disabled'?'selected':'' }}>Disabled</option></select><button class="btn btn-soft" type="submit">Filter</button></form><div style="height:12px"></div><div class="table-wrap"><table><thead><tr><th>Restaurant</th><th>Domain</th><th>Database</th><th>Period</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($tenants as $tenant)<tr><td><span class="tenant-name">{{ $tenant->name }}</span><span class="sub">{{ $tenant->email }}</span></td><td>{{ $tenant->domain }}</td><td>{{ $tenant->database }}</td><td>{{ $tenant->start }} → {{ $tenant->end }}</td><td><span class="badge {{ $tenant->status==='active'?'ok':'bad' }}">{{ $tenant->status }}</span></td><td><form method="POST" action="/superadmin/tenants/status" style="display:flex;gap:6px">@csrf<input type="hidden" name="id" value="{{ $tenant->id }}"><select name="status" style="border:1px solid #dfe9e5;border-radius:9px;padding:7px"><option value="active" {{ $tenant->status==='active'?'selected':'' }}>Active</option><option value="disabled" {{ $tenant->status==='disabled'?'selected':'' }}>Disabled</option></select><button class="btn btn-soft" type="submit">Save</button></form></td></tr>@empty<tr><td colspan="6" class="empty">No tenants found.</td></tr>@endforelse</tbody></table></div><div style="margin-top:12px">{{ $tenants->links() }}</div></div>
<div class="card"><div class="card-head"><div><h3>Create restaurant</h3><p>Creates the central tenant record, clones newtenantdb, finalizes the tenant baseline and provisions domain/TLS. The tenant stays disabled until provisioning succeeds.</p></div></div><form method="POST" action="/superadmin/new/store">@csrf<div class="field-grid"><div class="field"><label>Restaurant name</label><input name="name" value="{{ old('name') }}" required></div><div class="field"><label>Tenant domain</label><input name="domain" value="{{ old('domain') }}" placeholder="restaurant.paymydine.com" required></div><div class="field"><label>Database</label><input name="database" value="{{ old('database') }}" placeholder="restaurant" required></div><div class="field"><label>Email</label><input type="email" name="email" value="{{ old('email') }}" required></div><div class="field"><label>Phone</label><input name="phone" value="{{ old('phone') }}" required></div><div class="field"><label>Country</label><input name="country" value="{{ old('country','Germany') }}" required></div><div class="field"><label>Start date</label><input type="date" name="start" value="{{ old('start',now()->toDateString()) }}" required></div><div class="field"><label>End date</label><input type="date" name="end" value="{{ old('end',now()->addYear()->toDateString()) }}" required></div><div class="field"><label>Plan / type</label><input name="type" value="{{ old('type','People') }}" required></div><div class="field full"><label>Description</label><textarea name="description">{{ old('description') }}</textarea></div><div class="field full"><button class="btn btn-primary" type="submit">Create restaurant</button></div></div></form></div>
</div>
@endsection
