// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/menu">> = Specific
  const handler = {} as typeof import("../../app/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/payment/return/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment/return">> = Specific
  const handler = {} as typeof import("../../app/payment/return/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/preview/[themeId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preview/[themeId]">> = Specific
  const handler = {} as typeof import("../../app/preview/[themeId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preview">> = Specific
  const handler = {} as typeof import("../../app/preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/table/[tableId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/table/[tableId]">> = Specific
  const handler = {} as typeof import("../../app/table/[tableId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/valet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/valet">> = Specific
  const handler = {} as typeof import("../../app/valet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bootstrap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bootstrap">> = Specific
  const handler = {} as typeof import("../../app/api/bootstrap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/locale/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/locale">> = Specific
  const handler = {} as typeof import("../../app/api/locale/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/media/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/[...path]">> = Specific
  const handler = {} as typeof import("../../app/api/media/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/[...path]">> = Specific
  const handler = {} as typeof import("../../app/api/v1/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v2/frontend-theme/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v2/frontend-theme">> = Specific
  const handler = {} as typeof import("../../app/api/v2/frontend-theme/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/assets/media/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/assets/media/[...path]">> = Specific
  const handler = {} as typeof import("../../app/assets/media/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pmd-media/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/pmd-media/[...path]">> = Specific
  const handler = {} as typeof import("../../app/pmd-media/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/simple-theme/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/simple-theme">> = Specific
  const handler = {} as typeof import("../../app/simple-theme/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/storage/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/storage/[...path]">> = Specific
  const handler = {} as typeof import("../../app/storage/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tip-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/tip-settings">> = Specific
  const handler = {} as typeof import("../../app/tip-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/uploads/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/uploads/[...path]">> = Specific
  const handler = {} as typeof import("../../app/uploads/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/validate-coupon/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/validate-coupon">> = Specific
  const handler = {} as typeof import("../../app/validate-coupon/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vat-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/vat-settings">> = Specific
  const handler = {} as typeof import("../../app/vat-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
