import type { CustomerBootstrap, MenuItem } from '@/src/domain/model'
import type { ThemeId } from '@/src/themes/catalog'

const demoItems: MenuItem[] = [
  {
    id: '101',
    name: 'Seared Scallops',
    description: 'Citrus beurre blanc, pea puree and garden herbs.',
    price: 24,
    categoryId: 'starters',
    categoryName: 'Starters',
    imageUrl: '/demo/scallops.svg',
    gallery: ['/demo/scallops.svg'],
    allergens: ['Shellfish', 'Milk'],
    halal: false,
    vegetarian: false,
    vegan: false,
    available: true,
    stockQty: 16,
    prepTimeMinutes: 16,
    nutrition: { calories: 410, protein: 29, carbs: 14, fat: 27, sugar: 5, servingSize: '1 plate', disclaimer: null },
    options: [],
    isChefRecommended: true,
    isBestseller: true,
    popularityCount: 87,
  },
  {
    id: '102',
    name: 'Black Truffle Risotto',
    description: 'Aged parmesan, roasted mushrooms and truffle dust.',
    price: 36,
    categoryId: 'mains',
    categoryName: 'Mains',
    imageUrl: '/demo/risotto.svg',
    gallery: ['/demo/risotto.svg'],
    allergens: ['Milk'],
    halal: true,
    vegetarian: true,
    vegan: false,
    available: true,
    stockQty: 12,
    prepTimeMinutes: 24,
    nutrition: { calories: 680, protein: 18, carbs: 78, fat: 32, sugar: 7, servingSize: '1 bowl', disclaimer: null },
    options: [{
      id: 'truffle', name: 'Truffle', displayType: 'radio', required: false,
      values: [
        { id: 'standard', name: 'Standard', price: 0, isDefault: true },
        { id: 'extra', name: 'Extra shaved truffle', price: 8, isDefault: false },
      ],
    }],
    isChefRecommended: true,
    isBestseller: false,
    popularityCount: 52,
  },
  {
    id: '103',
    name: 'Saffron Chelo Kebab',
    description: 'Charcoal grilled fillet, saffron rice and blistered tomato.',
    price: 32.95,
    categoryId: 'grill',
    categoryName: 'Grill',
    imageUrl: '/demo/kebab.svg',
    gallery: ['/demo/kebab.svg'],
    allergens: [],
    halal: true,
    vegetarian: false,
    vegan: false,
    available: true,
    stockQty: 20,
    prepTimeMinutes: 22,
    nutrition: { calories: 790, protein: 52, carbs: 71, fat: 31, sugar: 6, servingSize: '1 plate', disclaimer: null },
    options: [],
    isChefRecommended: true,
    isBestseller: true,
    popularityCount: 113,
  },
  {
    id: '104',
    name: 'Miso Aubergine',
    description: 'White miso glaze, sesame, spring onion and pickled daikon.',
    price: 18,
    categoryId: 'vegan',
    categoryName: 'Vegan',
    imageUrl: '/demo/aubergine.svg',
    gallery: ['/demo/aubergine.svg'],
    allergens: ['Soy', 'Sesame'],
    halal: true,
    vegetarian: true,
    vegan: true,
    available: true,
    stockQty: 14,
    prepTimeMinutes: 15,
    nutrition: { calories: 340, protein: 9, carbs: 35, fat: 19, sugar: 18, servingSize: '1 plate', disclaimer: null },
    options: [],
    isChefRecommended: false,
    isBestseller: false,
    popularityCount: 29,
  },
  {
    id: '105',
    name: 'Charcoal Ribeye',
    description: 'Dry-aged beef, smoked butter, sea salt and grilled asparagus.',
    price: 42,
    categoryId: 'grill',
    categoryName: 'Grill',
    imageUrl: '/demo/ribeye.svg',
    gallery: ['/demo/ribeye.svg'],
    allergens: ['Milk'],
    halal: false,
    vegetarian: false,
    vegan: false,
    available: true,
    stockQty: 8,
    prepTimeMinutes: 28,
    nutrition: { calories: 910, protein: 71, carbs: 12, fat: 65, sugar: 4, servingSize: '350 g', disclaimer: null },
    options: [{
      id: 'doneness', name: 'Doneness', displayType: 'radio', required: true,
      values: [
        { id: 'medium_rare', name: 'Medium rare', price: 0, isDefault: true },
        { id: 'medium', name: 'Medium', price: 0, isDefault: false },
        { id: 'well_done', name: 'Well done', price: 0, isDefault: false },
      ],
    }],
    isChefRecommended: false,
    isBestseller: true,
    popularityCount: 78,
  },
  {
    id: '106',
    name: 'Grilled Octopus',
    description: 'Lemon, olive oil, chickpeas and Mediterranean herbs.',
    price: 24,
    categoryId: 'seafood',
    categoryName: 'Seafood',
    imageUrl: '/demo/octopus.svg',
    gallery: ['/demo/octopus.svg'],
    allergens: ['Molluscs'],
    halal: true,
    vegetarian: false,
    vegan: false,
    available: true,
    stockQty: 11,
    prepTimeMinutes: 19,
    nutrition: { calories: 465, protein: 38, carbs: 28, fat: 22, sugar: 4, servingSize: '1 plate', disclaimer: null },
    options: [],
    isChefRecommended: false,
    isBestseller: false,
    popularityCount: 41,
  },
  {
    id: '107',
    name: 'Pistachio Baklava',
    description: 'Rosewater syrup, pistachio layers and saffron ice cream.',
    price: 11,
    categoryId: 'desserts',
    categoryName: 'Desserts',
    imageUrl: '/demo/baklava.svg',
    gallery: ['/demo/baklava.svg'],
    allergens: ['Gluten', 'Nuts', 'Milk'],
    halal: true,
    vegetarian: true,
    vegan: false,
    available: true,
    stockQty: 18,
    prepTimeMinutes: 8,
    nutrition: { calories: 520, protein: 9, carbs: 61, fat: 27, sugar: 39, servingSize: '1 slice', disclaimer: null },
    options: [],
    isChefRecommended: false,
    isBestseller: true,
    popularityCount: 96,
  },
  {
    id: '108',
    name: 'Yuzu Midnight',
    description: 'Yuzu, tonic, black tea and smoked rosemary.',
    price: 13.5,
    categoryId: 'drinks',
    categoryName: 'Drinks',
    imageUrl: '/demo/cocktail.svg',
    gallery: ['/demo/cocktail.svg'],
    allergens: [],
    halal: true,
    vegetarian: true,
    vegan: true,
    available: true,
    stockQty: null,
    prepTimeMinutes: 5,
    nutrition: { calories: 115, protein: 0, carbs: 25, fat: 0, sugar: 20, servingSize: '250 ml', disclaimer: null },
    options: [],
    isChefRecommended: true,
    isBestseller: false,
    popularityCount: 48,
  },
]

export function createMockBootstrap(themeId: ThemeId = 'verdant_modern', host = 'preview.paymydine.local'): CustomerBootstrap {
  return {
    apiVersion: 'pmd-customer-bootstrap-v2',
    tenant: { id: 'preview', slug: 'preview', host },
    restaurant: {
      id: 'preview',
      name: 'Atelier Mimoza',
      description: 'A modern dining room built around seasonal ingredients and thoughtful hospitality.',
      logoUrl: '/brand/demo-restaurant.svg',
      faviconUrl: null,
      heroImageUrl: '/demo/scallops.svg',
      phone: '+49 30 555 0101',
      whatsapp: '+49 30 555 0101',
      address: 'Berlin, Germany',
      currency: 'EUR',
      locale: 'en',
      timezone: 'Europe/Berlin',
      footerText: 'Thank you for dining with us.',
    },
    theme: { id: themeId, version: 'preview-1', rawAdminThemeId: themeId, options: {} },
    locales: { defaultLocale: 'en', enabledLocales: ['en', 'de', 'fa', 'tr', 'ja'] },
    socialLinks: [
      { platform: 'instagram', label: 'Instagram', url: 'https://instagram.com', enabled: true },
      { platform: 'website', label: 'Website', url: 'https://paymydine.com', enabled: true },
      { platform: 'google', label: 'Google', url: 'https://google.com', enabled: true },
    ],
    features: { waiterCall: true, valet: true, tableOrdering: true, splitBill: true, tips: true, coupons: true, socialLinks: true },
    tax: { enabled: true, percentage: 19, includedInMenuPrice: true },
    tips: { enabled: true, presets: [0, 5, 10, 15] },
    serviceCharge: { enabled: false, type: 'percentage', value: 0, label: 'Service charge' },
    table: { valid: true, id: '7', number: '07', name: 'Table 07', qr: 'preview-table-07', locationId: 1 },
    menu: {
      categories: [
        { id: 'starters', name: 'Starters', description: 'Small beginnings', imageUrl: null, priority: 1 },
        { id: 'mains', name: 'Mains', description: 'Signature plates', imageUrl: null, priority: 2 },
        { id: 'grill', name: 'Grill', description: 'Fire and charcoal', imageUrl: null, priority: 3 },
        { id: 'seafood', name: 'Seafood', description: 'From the coast', imageUrl: null, priority: 4 },
        { id: 'vegan', name: 'Vegan', description: 'Plant-led', imageUrl: null, priority: 5 },
        { id: 'desserts', name: 'Desserts', description: 'Sweet endings', imageUrl: null, priority: 6 },
        { id: 'drinks', name: 'Drinks', description: 'Cocktails and zero-proof', imageUrl: null, priority: 7 },
      ],
      items: demoItems,
      highlights: { showChefRecommendations: true, showBestsellers: true, chefTitle: "Chef's selections", bestsellerTitle: 'Most ordered tonight' },
      cacheVersion: 'preview-1',
    },
    payments: [
      { code: 'card', name: 'Card', providerCode: 'stripe', enabled: true, priority: 1 },
      { code: 'paypal', name: 'PayPal', providerCode: 'paypal', enabled: true, priority: 2 },
      { code: 'cash', name: 'Cash', providerCode: null, enabled: true, priority: 3 },
    ],
    activeOrder: null,
  }
}
